

--
-- Estructura de tabla para la tabla `RLDV2025`
--


CREATE TABLE `RLDV2025` (
  `MDREIDRE` int NOT NULL COMMENT 'SECUENCIA DEL REGISTRO O LICENCIA',
  `FACIDXXX` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DE LA FACTURA (DSVCYYYY)',
  `PROIDXXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CODIGO DEL PRODUCTO',
  `CLIIDXXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NIT CLIENTE',
  `IDPROXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DEL PROVEEDOR(CIPO0050)',
  `DESIDXXX` int NOT NULL COMMENT 'ID DE LA IENTIDAD(CIPO0010)',
  `IDARCHXX` int NOT NULL COMMENT 'ID DEL ARCHIVO EN GENIO(GESTOR.DOCCYYYY)',
  `NUMSOLIC` varchar(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NUMERO DE SOLICITUD',
  `NUMVBXX` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NUNMERO DE VISTO BUENO',
  `CONCVBXX` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CONCEPTO DE VISTO BUENO',
  `FECAPRON` datetime NOT NULL COMMENT 'FECHA DE APROBACION O NEGACION',
  `FECVECIX` date NOT NULL COMMENT 'FECHA DE VENCIMIENTO',
  `OBSDSVBX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'OBSERVACIONES O DESCRIPCION VISTO BUENO',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='VUCE, PRODUCTO VS VISTOS BUENOS';

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `RLDV2025`
--
ALTER TABLE `RLDV2025`
  ADD PRIMARY KEY (`MDREIDRE`,`FACIDXXX`,`PROIDXXX`,`CLIIDXXX`,`IDPROXXX`,`DESIDXXX`),
  ADD KEY `MDREIDRE` (`MDREIDRE`),
  ADD KEY `FACIDXXX` (`FACIDXXX`),
  ADD KEY `PROIDXXX` (`PROIDXXX`),
  ADD KEY `CLIIDXXX` (`CLIIDXXX`),
  ADD KEY `IDPROXXX` (`IDPROXXX`),
  ADD KEY `DESIDXXX` (`DESIDXXX`);
COMMIT;