

CREATE TABLE IF NOT EXISTS `MDSE2025` (
  `DOCNROXX` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'IDENTIFICACION DE LA OPERACION',
  `NUMSAEXX` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Numero de la SAE',
  `NUMSAENS` smallint(6) NOT NULL COMMENT 'NUMERO DE SERIE CASILLA 150',
  `NUMSAEPR` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NUMERO DE PROGRAMA CASILLA 151',
  `NUMSAERE` enum('','SI','NO') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'REPOSICION CASILLA 152',
  `NUMSAECI` smallint(6) NOT NULL COMMENT 'No de cuadro insumo producto (CIP) casilla 153',
  `NUMSAEPO` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NO. DE PRODUCTO CASILLA 154',
  `NUMSAECP` decimal(7,2) NOT NULL COMMENT 'CANTIDAD PRODUCTO A EXPORTAR POR CIP CASILLA 155',
  `NUMSAEVN` decimal(7,7) NOT NULL COMMENT 'valor agregado nacional (VAN) en USD casilla 156',
  `NUMSAEVE` decimal(7,7) NOT NULL COMMENT 'VALOR INSUMO EXTERNO (VIE) EN USD CASILLA 157',
  `REGUSRXX` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creación del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creación del Registro',
  `REGUSRMX` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificación',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificación del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificación del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`DOCNROXX`,`NUMSAEXX`,`NUMSAENS`),
  KEY `DOCNROXX` (`DOCNROXX`),
  KEY `NUMSAEXX` (`NUMSAEXX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Datos de SAE y DEX VS MANEJOS ESPECIALES';


