

SELECT t2024.TABLE_NAME AS Tablas_Faltantes_2025
	  
      FROM ( 
			SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
			WHERE TABLE_SCHEMA = 'WMSLLC'
			AND TABLE_NAME LIKE '%2024'
		   ) AS  t2024

      LEFT JOIN 
	      (
		  SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
		  WHERE TABLE_SCHEMA = 'WMSLLC'
		  AND TABLE_NAME LIKE '%2025'
	      ) AS t2025

		  ON SUBSTRING(t2024.TABLE_NAME, 1, LENGTH(t2024.TABLE_NAME)-4) = SUBSTRING(t2025.TABLE_NAME, 1, LENGTH(t2025.TABLE_NAME)-4)
		  WHERE t2025.TABLE_NAME IS NULL
          
