

SELECT CONCAT('UPDATE CIPO0118 SET GRUEGRMX = "', GRUEGRMX, '" WHERE GRUEMPID = "', GRUEMPID, '";') AS t0 FROM CIPO0118; 




SELECT 
    CONCAT(
        'UPDATE CIMS0043 SET CIUIDXXX = "', CIUIDXXX, 
        '" WHERE PAIIDXXX = "', PAIIDXXX, 
        '" AND CIUDESXX = "', CIUDESXX, 
        '" AND LENGTH(CIUIDXXX) < 2;'
    ) AS update_query
FROM 
    CIMS0043 
WHERE 
    PAIIDXXX LIKE '%CO%' 
    AND LENGTH(CIUIDXXX) < 2;

