

-- ver registros en cada particion

SELECT PARTITION_NAME, TABLE_ROWS 
FROM INFORMATION_SCHEMA.PARTITIONS 
WHERE TABLE_NAME = 'TARC2025_NEW';

-- ver la particiones de la tabla 

SELECT 
    PARTITION_NAME, 
    TABLE_ROWS, 
    PARTITION_ORDINAL_POSITION, 
    PARTITION_METHOD, 
    PARTITION_EXPRESSION 
FROM INFORMATION_SCHEMA.PARTITIONS 
WHERE TABLE_NAME = 'TARC2025_NEW';	

-- validar la distribucion  de datos en cada particion 

SELECT PARTITION_NAME, TABLE_ROWS 
FROM INFORMATION_SCHEMA.PARTITIONS 
WHERE TABLE_NAME = 'TARC2025_NEW';

