
-- ALTERAR EL COTEJAMIENTO DE 1 UNA TABLA
ALTER TABLE TABLA_NOMBRE
CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ALTERAR EL COTEJAMIENTO SOLO APLICA PARA NUEVAS TABLAS  NO EXISTENTES

ALTER DATABASE mi_base_de_datos
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

-- ESTE SELECT PERMITE CAMBIAR EL COTEJAMIENTO CREANDO EL ALTER CONCATENANDO LA FUNCION  X  CANTIDAD DE ALTER PARA LA TABLAS 
SELECT CONCAT(
    'ALTER TABLE `', TABLE_NAME, 
    '` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
) AS comando_sql
FROM information_schema.tables
WHERE table_schema = 'CIMATEST'
  AND TABLE_NAME LIKE '%2025';

