
-- # TABLAS CON INFORMACION DIFERENTE DE 0
SELECT 
	COUNT(TABLE_NAME) AS N_TABLAS
FROM 
    INFORMATION_SCHEMA.TABLES 
WHERE 
    TABLE_SCHEMA = 'WMS'
    AND TABLE_ROWS != 0
    AND TABLE_NAME  like '%2025';
    
--  TABLAS QUE CONTENGAN INFORMACION DIFERENTE DE 0
SELECT 
	TABLE_NAME
FROM 
    INFORMATION_SCHEMA.TABLES 
WHERE 
    TABLE_SCHEMA = 'WMS'
    AND TABLE_ROWS != 0
    AND TABLE_NAME  like '%2025';