USE sakila;

SELECT 
TABLE_NAME,
CREATE_TIME
FROM information_schema.tables
WHERE TABLE_SCHEMA='KAIZEN'
AND TABLE_NAME LIKE'%2025';


SELECT 
COUNT(TABLE_NAME)

FROM information_schema.tables
WHERE TABLE_SCHEMA='GRM'
AND TABLE_NAME LIKE'%2025'
