DROP TABLE IF EXISTS `DSVD2025`;
CREATE TABLE `DSVD2025` (
  `CLIIDXXX` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del cliente',
  `IDPROXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DEL PROVEEDOR (CIPO0050)',
  `FACIDXXX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'numero de la factura',
  `SECITEXX` int NOT NULL COMMENT 'SECUENCIA DEL ITEM',
  `SECITE2X` int NOT NULL COMMENT 'secuencia dos del item',
  `PROIDXXX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CODIGO DEL PRODUCTO (CIPO0141)',
  `PROID2XX` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Codigo de producto DOS',
  `PRODESFA` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DESCRIPCION SEGUN FACTURA',
  `SUBIDSUG` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'SUBPARTIDA SUGERIA',
  `PAIDORXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'id del pais',
  `ESTMERXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ESTADO DE LA MERCANCIA',
  `CODESTID` varchar(1) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DEL ESTADO DE LA MERCANCIA',
  `ANIOFABX` int NOT NULL COMMENT 'año de fabricacion',
  `FPIIDXXX` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Cod Forma Pago',
  `CANDAVXX` int NOT NULL COMMENT 'CANTIDAD DAV',
  `UNIIDXXX` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DE LA UNIDAD',
  `CANITEXX` int NOT NULL COMMENT 'CANTIDAD ITEM',
  `VALUNIIT` decimal(12,5) NOT NULL COMMENT 'valor unitario',
  `VALTOTIT` decimal(14,5) NOT NULL COMMENT 'valor Total',
  `PESBRUIT` decimal(12,5) NOT NULL COMMENT 'peso bruto',
  `PESNETIT` decimal(12,5) NOT NULL COMMENT 'peso neto',
  `ORDCOMIT` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'orden de compra',
  `PEDITEXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'pedido del item',
  `FOBGASIT` decimal(12,5) NOT NULL COMMENT 'valor FOB gastos facturados',
  `FLEGASIT` decimal(12,5) NOT NULL COMMENT 'valor FLETE gastos facturados',
  `CONGASIT` decimal(12,5) NOT NULL COMMENT 'valor CONEXOS gastos facturados',
  `SEGGASIT` decimal(12,5) NOT NULL COMMENT 'valor SEGUROS gastos facturados',
  `VARGASIT` decimal(12,5) NOT NULL COMMENT 'valor VARIOS gastos facturados',
  `NOMCOMIT` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'nombre comercial',
  `MARCOMIT` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'marca',
  `TIPITEXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'TIPO',
  `CLAITEXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CLASE',
  `MODITEXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'MODELO',
  `REFITEXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'REFERENCIA',
  `OTRITEXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'OTRAS CARACTERISTICAS',
  `BATNUMXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BATCH NUMBER',
  `INFADIIT` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'INFORMACION ADICIONAL DEL ITEM',
  `DELNOTIT` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DELIVERY NOTE',
  `SAITFAXX` int NOT NULL COMMENT 'SALDO DEL ITEM',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='DETALLE DE SALDOS DE FACTURA' ROW_FORMAT=DYNAMIC;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `DSVD2025`
--
ALTER TABLE `DSVD2025`
  ADD PRIMARY KEY (`CLIIDXXX`,`FACIDXXX`,`SECITEXX`,`IDPROXXX`) USING BTREE,
  ADD KEY `CLIIDXXX` (`CLIIDXXX`) USING BTREE,
  ADD KEY `FACIDXXX` (`FACIDXXX`) USING BTREE,
  ADD KEY `CODESTID` (`CODESTID`) USING BTREE,
  ADD KEY `FPIIDXXX` (`FPIIDXXX`) USING BTREE,
  ADD KEY `UNIIDXXX` (`UNIIDXXX`) USING BTREE,
  ADD KEY `IDPROXXX` (`IDPROXXX`),
  ADD KEY `PROIDXXX` (`PROIDXXX`);
COMMIT;
