
CREATE TABLE `DEND2025` (
  `KEYDENSX` varchar(50) NOT NULL,
  `PARTNUMX` varchar(25) DEFAULT NULL COMMENT 'Parte número Avianca',
  `DESCPNXX` tinytext COMMENT 'Descripcion carga o pedido',
  `QUANTITY` varchar(10) DEFAULT NULL COMMENT 'Cantidad',
  `PRECIOXX` varchar(25) DEFAULT NULL COMMENT 'Precio',
  `FECESTXX` date DEFAULT NULL COMMENT 'Fecha Estimada',
  `FECCONXX` date DEFAULT NULL COMMENT 'Fecha Confirmada',
  `SEMANAXX` varchar(10) DEFAULT NULL COMMENT 'Semana',
  `FECSAXXX` date DEFAULT NULL COMMENT 'Fecha SA',
  `SHIPFROM` varchar(25) DEFAULT NULL COMMENT 'Ship From (País)',
  `STATUSXX` varchar(25) DEFAULT NULL COMMENT 'Estado',
  `BOXNUMXX` varchar(25) DEFAULT NULL COMMENT 'Box Number',
  `SAXXXXXX` varchar(10) DEFAULT NULL COMMENT 'SA',
  `SHIPVIAX` varchar(25) DEFAULT NULL COMMENT 'Ship via (Modo de transporte)',
  `SHIPTOXX` varchar(25) DEFAULT NULL COMMENT 'Ship to (Modo de transporte)',
  `FECPICKX` date DEFAULT NULL COMMENT 'Fecha Pick up',
  `AWBTRANS` varchar(25) DEFAULT NULL COMMENT 'AWB Transito',
  `AWBMASXX` varchar(25) DEFAULT NULL COMMENT 'AWB Master',
  `SHIPMENT` varchar(25) DEFAULT NULL COMMENT 'Shipment',
  `FECETDXX` date DEFAULT NULL COMMENT 'Fecha Estimada Salida',
  `FECETAXX` date DEFAULT NULL COMMENT 'Fecha Estimada Llegada',
  `FECATDXX` date DEFAULT NULL COMMENT 'Fecha Salida Confirmada',
  `FECATAXX` date DEFAULT NULL COMMENT 'Fecha Llegada Confirmada',
  `COMEXCOL` varchar(25) DEFAULT NULL COMMENT 'Status Comex Col',
  `OBSERVAX` tinytext COMMENT 'Observaciones',
  `FECRECIB` date DEFAULT NULL COMMENT 'Fecha recibido - Almacen Destino',
  `FECESTDI` date DEFAULT NULL COMMENT 'Fecha Estimada Disponible Inventario',
  `PERFORMX` varchar(25) DEFAULT NULL COMMENT 'Performance',
  `FECLIMIT` date DEFAULT NULL COMMENT 'Fecha límite',
  `NOTAXXXX` tinytext COMMENT 'Nota',
  `SUBPEDPN` varchar(50) DEFAULT NULL COMMENT 'Sub pedido PN',
  `SUBPEDQT` int(11) DEFAULT NULL COMMENT 'Sub pedido QTY',
  `SUBPEDMU` varchar(10) DEFAULT NULL COMMENT 'Sub pedido Measure_Unit',
  `AIRCRAFT` varchar(20) DEFAULT NULL COMMENT 'Aircraft',
  `CURRENCY` varchar(10) DEFAULT NULL COMMENT 'Currency',
  `TARGETDT` date DEFAULT NULL COMMENT 'Target DT',
  `VENDORXX` varchar(70) DEFAULT NULL COMMENT 'Proveedor',
  `REGUSRXX` varchar(20) NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion',
  `REGESTXX` enum('ACTIVO','INACTIVO') NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Detalle Densificacion Avianca';
COMMIT;


