

CREATE TABLE `CIMS0024` (
  `MODIDXXX` int NOT NULL COMMENT 'ID del modulo',
  `PROIDXXX` int NOT NULL COMMENT 'ID del proceso',
  `CLATARID` int NOT NULL COMMENT 'ID DE LA CLASIFICACION',
  `CRIASIID` int NOT NULL COMMENT 'ID del criterio',
  `USRIDXXX` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del usuario',
  `CRIRESXX` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'criterio seleccionado',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='PARAMETRIZACION ADMINISTRACION DE LA TAREA,\r\nCRITERIOS DE ASIGNACION VS USUARIOS' ROW_FORMAT=DYNAMIC;


ALTER TABLE `CIMS0024`
  ADD PRIMARY KEY (`MODIDXXX`,`PROIDXXX`,`CLATARID`,`CRIASIID`,`USRIDXXX`,`CRIRESXX`) USING BTREE,
  ADD KEY `MODIDXXX` (`MODIDXXX`) USING BTREE,
  ADD KEY `PROIDXXX` (`PROIDXXX`) USING BTREE,
  ADD KEY `CLATARID` (`CLATARID`) USING BTREE,
  ADD KEY `CRIASIID` (`CRIASIID`) USING BTREE,
  ADD KEY `USRIDXXX` (`USRIDXXX`) USING BTREE,
  ADD KEY `CRIRESXX` (`CRIRESXX`);
COMMIT;



ALTER TABLE `CIMS0024`
ADD COLUMN ORDASIGX INT NOT NULL COMMENT 'ORDEN DE LA ASIGNACION' AFTER CRIASIID;

ALTER TABLE `CIMS0024`
DROP PRIMARY KEY;

ALTER TABLE `CIMS0024`
ADD PRIMARY KEY (`MODIDXXX`,`PROIDXXX`,`CLATARID`,`CRIASIID`,`USRIDXXX`,`CRIRESXX`,`ORDASIGX`) USING BTREE;

ALTER TABLE `CIMS0024`
ADD KEY  IDX_ORDASIGX (`ORDASIGX`) ;
