CREATE TABLE `CIPO0049` (
  `CLIIDXXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nit cliente',
  `IDPROXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DEL PROVEEDOR',
  `NATIDXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Cod Naturaleza',
  `CLIPROFE` enum('','1','2','3','4') COLLATE utf8mb4_unicode_ci NOT NULL,
  `CLIPROBA` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'bandera que indica si  existen resoluciones dian de ajustes de valor permanente  o anticipadas de valoracion',
  `CLIPROGL` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'bandera que indica si  existen NEGOCIACION GLOBAL',
  `CLIPROCF` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'bandera que indica si existen tipos de cambios fijos',
  `PRCLINTX` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'bandera que indica si la transaccion comercial cuenta con partiicipacion de algun intermediario',
  `PROCLIPI` enum('','PERSONA NATURAL','PERSONA JURIDICA') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'bandera que indica el tipo de persona intermediaria',
  `PRCLPAXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'primer apellido',
  `PRCLSAXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'segundo apellido',
  `PRCLPNXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'primer nombre',
  `PRCLONXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'otros nombres',
  `PRCLRAIN` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'RAZON SOCIAL DEL INTERMEDIARIO',
  `PAIIDXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del pais',
  `DEPIDXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'id del departamento',
  `CIUIDXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'id de la ciudad',
  `PRCLDIRX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'direccion del intermediario',
  `PRCLTIPX` enum('','DE VENTA','DE COMPRA','CORREDOR','OTRO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'indica el tipo de itermediario',
  `PRCLTIIN` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'especificacion del tipo de intermediario',
  `PRCLBNER` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'bandera que indica si existen restricciones a la cesion o utilizacion de las mercancias',
  `CODRESTX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Codigo Restriccion',
  `PRCLPREX` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'BANDERA QUE INDICA SI EXISTEN CONDICIONES O CONTRAPRESTACIONES QUE AFECTAN EL VALOR DE LA MERCANCIA',
  `CODCONDX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID de la condicion o contraprestacion',
  `PRCLESCT` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'especificacion de condicion o contraindicacion',
  `PRCLBNVC` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'BANDERA QUE INDICA SI PUEDE DETERMINARSE EL VALOR DE LAS CONDICIONES O CONTRAPRESTACIONES',
  `PRCLBNCA` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'BANDERA QUER INDICA SI EXISTEN CANONES Y DERECHOS DE LICENCIA',
  `PRCLBNRE` enum('','SIEMPRE','ALGUNAS VECES') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'bandera que indica si aplica regalias',
  `PRCLBNRM` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'BANDERA QUE INDICA SI APLICA REGALIAS DIFERENCIALES POR MARCA',
  `PRCLCORE` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI EXISTEN CONTRATOS DE PAGOS DE REGALIAS',
  `PRCLREVE` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI EXISTEN REVERSIONES AL VENDEDOR',
  `PRCLBNEP` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI EXISTE VINCULACION CLIENTE Y PROVEEDOR',
  `CODVINID` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DEL Codigo DE VINCULACION IMPORTADOR PROVEEDOR',
  `PRCLBNIP` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI INFLUYE LA VINCULACION ENTRE IMPORTADOR PROVEEDOR EL PRECIO DE LA MERCANCIA',
  `PRCLEXVC` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI EXISTEN VALORES CRITERIO',
  `PRCLBNPR` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI EXISTEN PAGOS RETROACTIVOS',
  `MONIDXXX` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID de la moneda(CIPO0022)',
  `CLIPROCG` enum('','CONTRATO GLOBAL','FACTURA') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA EL DOCUMENTO QUE SOPORTA EL CAMBIO FIJO',
  `CONDESXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Descripcion Contrato',
  `MDDACVPR` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI TIENEN CARACTER DE VALOR PROVISIONAL',
  `MDDAEXVC` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI EXISTEN VALORES CRITERIO CASILLA 90',
  `CONTRAID` smallint NOT NULL COMMENT 'ID del contrato ',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CLIENTE, PROVEEDOR VS CONDICIONES DE NEGOCIACION' ROW_FORMAT=DYNAMIC;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `CIPO0049`
--
ALTER TABLE `CIPO0049`
  ADD PRIMARY KEY (`CLIIDXXX`,`IDPROXXX`) USING BTREE,
  ADD KEY `CLIIDXXX` (`CLIIDXXX`) USING BTREE,
  ADD KEY `IDPROXXX` (`IDPROXXX`) USING BTREE,
  ADD KEY `NATIDXXX` (`NATIDXXX`) USING BTREE,
  ADD KEY `PAIIDXXX` (`PAIIDXXX`) USING BTREE,
  ADD KEY `DEPIDXXX` (`DEPIDXXX`) USING BTREE,
  ADD KEY `CIUIDXXX` (`CIUIDXXX`) USING BTREE,
  ADD KEY `CODREST` (`CODRESTX`) USING BTREE,
  ADD KEY `CODCONDX` (`CODCONDX`) USING BTREE,
  ADD KEY `MONIDXXX` (`MONIDXXX`);
COMMIT;


-- ACTUALIZACION

ALTER TABLE  CIPO0049
ADD COLUMN `CONDESXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Descripcion Contrato'AFTER CLIPROCG;
ALTER TABLE  CIPO0049
ADD COLUMN `MDDACVPR` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI TIENEN CARACTER DE VALOR PROVISIONAL' AFTER CONDESXX;
ALTER TABLE  CIPO0049
ADD COLUMN`MDDAEXVC` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI EXISTEN VALORES CRITERIO CASILLA 90' AFTER MDDACVPR;
ALTER TABLE  CIPO0049
ADD COLUMN `CONTRAID` smallint NOT NULL COMMENT 'ID del contrato ' AFTER MDDAEXVC;