-- TABLA CIMS0070 - PROYECTO CIMA 

Create table CIMS0070(
  OBJIDXXX SMALLINT (4) NOT NULL COMMENT 'ID DEL OBJETIVO ',
  OBJESPID SMALLINT (4) NOT NULL COMMENT 'ID DEL OBJETIVO ',
  RESCLAXX SMALLINT (4) NOT NULL COMMENT 'ID DEL OBJETIVO ',
  CARIDXXX SMALLINT (4) NOT NULL COMMENT 'ID DEL OBJETIVO ',
  REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
  REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
  REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
  REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  
  PRIMARY KEY (`OBJIDXXX`, `OBJESPID`, `RESCLAXX`, `CARIDXXX`) COMMENT 'Clave primaria compuesta',
  KEY idx_OBJIDXXX (OBJIDXXX),
  KEY idx_OBJESPID (OBJESPID),
  KEY idx_RESCLAXX (RESCLAXX),
  KEY idx_CARIDXXX (CARIDXXX)
  
  ) COMMENT = 'OBJETIVO GENERAL Y OBJETIVOS ESPECIFICOS Y RESULTADOS CLAVE VS CARGOS';