 -- TABLA CIMS0072 - PROYECTO CIMA 
  
  CREATE TABLE CIMS0072 (
  COTIDXX SMALLINT PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT 'ID DEL CONTROLADOR' ,
  COTDESXX TINYTEXT  NOT NULL COMMENT 'DESCRIPCION DEL CONTROLADOR',
  MODIDXXX  INT NOT NULL  COMMENT 'ID DEL MODULO CIMS0003',
  PROIDXXX INT NOT NULL  COMMENT'ID DEL PROCESO CIMS0004',
  DOCMTXXX ENUM ('','AEREO','MARITIMO ','TERRESTRE','TRANSITO','NO APLICA') NOT NULL COMMENT 'MODO DE TRANSPORTE',
  DOCTIPTI ENUM ('','AEREO','MARITIMO ','TERRESTRE','TRANSITO','NO APLICA') NOT NULL COMMENT 'MODO DE TRANSPORTE INTERNACIONAL',
  REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
  REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
  REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
  REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del ROBOT',
  REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'

  
  ) AUTO_INCREMENT = 100 ENGINE = InnoDB COMMENT = 'CONTRLADOR'
  

  
  