-- TABLA CIMS0071 - PROYECTO CIMA  	
  
  CREATE TABLE CIMS0071 (
  USRIDXXX VARCHAR(15)  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DEL USUARIO CIMS0001',
  MODIDXXX INT(9) NOT NULL COMMENT 'ID DEL MODULO CIMS0003',
  PROIDXXX INT(9) NOT NULL COMMENT 'ID DEL PROCESO CIMS0004',
  COLUMXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NOMBRE DE LA COLUMNA',
  ORDENXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ORDEN DE LA COLUMNAS ',
  REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
  REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
  REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
  REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del ROBOT',
  REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  
   PRIMARY KEY (`USRIDXXX`, `MODIDXXX`, `PROIDXXX`, `COLUMXX`,`ORDENXX`) COMMENT 'Clave primaria compuesta',
  KEY idx_USRIDXXX (USRIDXXX),
  KEY idx_MODIDXXX (MODIDXXX),
  KEY idx_PROIDXXX (PROIDXXX),
  KEY idx_COLUMXX (COLUMXX),
  KEY idx_ORDENXX (ORDENXX)
  
  )COMMENT = 'MODULO,PROCESO Y USUARIO VS ORDEN DE COLUMNAS';