

CREATE TABLE `MDOE2025` (
  `SUCIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL,
  `DOCTIPXX` varchar(12) COLLATE utf8_unicode_ci NOT NULL,
  `DOCNROXX` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `DOCSUFXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL,
  `DOCPESTX` varchar(5) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Identificador o Peso del Estado',
  `DOCESTXX` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Estado DO',
  `NOTISTBK` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Notificar estado a RIO',
  `DOCDESTX` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Documentos del Estado',
  `DOCFESTX` date NOT NULL COMMENT 'Fecha del Estado',
  `DOCHESTX` time NOT NULL COMMENT 'Hora del Estado',
  `REGFECMR` date NOT NULL COMMENT 'Fecha de Modificacion del Registro Para RIO',
  `REGHORMR` time NOT NULL COMMENT 'Hora de Modificacion del Registro Para RIO',
  `REGFECXX` date NOT NULL,
  `REGHORXX` time NOT NULL,
  `REGMODXX` date NOT NULL,
  `REGUSRXX` varchar(12) COLLATE utf8_unicode_ci NOT NULL,
  `REGESTXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFICADO'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Estados del DO' ROW_FORMAT=DYNAMIC;

--
-- Disparadores `MDOE2025`
--
DELIMITER $$
CREATE TRIGGER `MDOE2025_INSERT` BEFORE INSERT ON `MDOE2025` FOR EACH ROW BEGIN
IF (NEW.DOCESTXX = "TRAMITE FINALIZADO" OR NEW.DOCESTXX = "PROFORMA/PENDIENTE GENERACION FACTURA") THEN
    INSERT IGNORE INTO GRM.`INDAGEND` (`TRAMITEX`,`TABLAXXX`,`CAMPOXXX`,`REGUSRXX`,`REGFECXX`,`REGHORXX`,`REGFECMX`,`REGHORMX`,`REGESTXX`) 
    VALUES (NEW.DOCNROXX,"MDOEYYYY","DOCESTXX","1000",NOW(),NOW(),NOW(),NOW(),"ACTIVO");  
  END IF;
  IF (NEW.DOCPESTX = "80") THEN
    INSERT IGNORE INTO GRM.`INDAGEND` (`TRAMITEX`,`TABLAXXX`,`CAMPOXXX`,`REGUSRXX`,`REGFECXX`,`REGHORXX`,`REGFECMX`,`REGHORMX`,`REGESTXX`) 
    VALUES (NEW.DOCNROXX,"MDOEYYYY","DOCFEANT","1000",NOW(),NOW(),NOW(),NOW(),"ACTIVO"); 
    INSERT IGNORE INTO GRM.`INDAGEND` (`TRAMITEX`,`TABLAXXX`,`CAMPOXXX`,`REGUSRXX`,`REGFECXX`,`REGHORXX`,`REGFECMX`,`REGHORMX`,`REGESTXX`) 
    VALUES (NEW.DOCNROXX,"MDOEYYYY","DOCFEANT_I","1000",NOW(),NOW(),NOW(),NOW(),"ACTIVO"); 	
  END IF;
  
   IF (NEW.DOCESTXX = "ENTREGA URGENTE FINALIZADA") THEN
    INSERT IGNORE INTO GRM.`INDAGEND` (`TRAMITEX`,`TABLAXXX`,`CAMPOXXX`,`REGUSRXX`,`REGFECXX`,`REGHORXX`,`REGFECMX`,`REGHORMX`,`REGESTXX`) 
    VALUES (NEW.DOCNROXX,"MDOEYYYY","DOESTURF","1000",NOW(),NOW(),NOW(),NOW(),"ACTIVO");  
  END IF;
  IF (NEW.DOCESTXX = "FACTURACION AUTORIZADA") THEN
    INSERT IGNORE INTO GRM.`INDAGEND` (`TRAMITEX`,`TABLAXXX`,`CAMPOXXX`,`REGUSRXX`,`REGFECXX`,`REGHORXX`,`REGFECMX`,`REGHORMX`,`REGESTXX`) 
    VALUES (NEW.DOCNROXX,"MDOEYYYY","DOESTAUF","1000",NOW(),NOW(),NOW(),NOW(),"ACTIVO");  
    INSERT IGNORE INTO GRM.INDAGEND (TRAMITEX,TABLAXXX,CAMPOXXX,REGUSRXX,REGFECXX,REGHORXX,REGFECMX,REGHORMX,REGESTXX)
VALUES (NEW.DOCNROXX,"MDOEYYYY","DOESTAUF_I","1000",NOW(),NOW(),NOW(),NOW(),"ACTIVO");
  END IF;
  IF (NEW.DOCPESTX = "160") THEN
  	UPDATE GRM.MDOS2025 SET DOCESTBK = "Cerrado", DOCESTUL = "TRAMITE FINALIZADO" WHERE DOCNROXX = NEW.DOCNROXX;
  END IF;


SET NEW.`REGFECMR`= NOW(); 
SET NEW.`REGHORMR`= NOW();
 

END
$$
DELIMITER ;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `MDOE2025`
--
ALTER TABLE `MDOE2025`
  ADD PRIMARY KEY (`DOCNROXX`,`DOCPESTX`,`REGFECXX`,`REGHORXX`,`REGUSRXX`) USING BTREE,
  ADD KEY `DOCTIPXX` (`DOCTIPXX`) USING BTREE,
  ADD KEY `SUCIDXXX` (`SUCIDXXX`) USING BTREE,
  ADD KEY `DOCNROXX` (`DOCNROXX`,`DOCESTXX`) USING BTREE;
COMMIT;


