

CREATE TABLE `SOTC2025` (
  `TARIDXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ID TAREA',
  `TARSEQXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'SECUENCIA TAREA',
  `TARDESXX` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'DESCRIPCION DE LA TAREA',
  `USRIDDES` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Usuario Destino',
  `REGUSRXX` varchar(12) COLLATE utf8_unicode_ci NOT NULL COMMENT 'USUARIO',
  `REGFECXX` date NOT NULL DEFAULT '0000-00-00' COMMENT 'FECHA DE RESGISTRO',
  `REGMODXX` date NOT NULL DEFAULT '0000-00-00' COMMENT 'FECHA DE MODIFICACION',
  `REGHORXX` varchar(5) COLLATE utf8_unicode_ci NOT NULL COMMENT 'HORA DE CREACION DE REGISTRO',
  `REGESTXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ESTADO',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFICADO'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `SOTC2025`
--
ALTER TABLE `SOTC2025`
  ADD PRIMARY KEY (`TARIDXXX`,`TARSEQXX`) USING BTREE;
COMMIT;

