

CREATE TABLE `CIMS0065` (
  `OBJIDXXX` smallint NOT NULL COMMENT 'ID DEL OBJETIVO',
  `OBJDESXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DESCRIPCION DEL OBJETIVO',
  `OBJAPLXX` enum('','IMPORTACION','EXPORTACION','TRANSITO','REGISTRO','DOCUMENTO DE TRANSPORTE','DOCUMENTO SOPORTE DE VALOR') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'TIPO DE OPERACION AL QUE\r\nAPLICA',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OBJETIVOS GENERALES';

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `CIMS0065`
--
ALTER TABLE `CIMS0065`
  ADD PRIMARY KEY (`OBJIDXXX`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `CIMS0065`
--
ALTER TABLE `CIMS0065`
  MODIFY `OBJIDXXX` smallint NOT NULL AUTO_INCREMENT COMMENT 'ID DEL OBJETIVO';
COMMIT;


