-- ALTER COLUM  CIPO0050

ALTER TABLE CIPO0050
MODIFY COLUMN `PROCONVE` ENUM('', '1', '2', '3') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT 'CODIGO DE CONDICION DEL VENDEDOR';


