-- INDICES AGREGADOS CIPO0203

ALTER TABLE `CIPO0203`
ADD KEY idx_PARSUBXX (PARSUBXX),
ADD KEY idx_ARMSUBXX (ARMSUBXX),
ADD KEY idx_ANDSUBXX (ANDSUBXX),
ADD KEY idx_SUBSUBXX (SUBSUBXX),
ADD KEY idx_SUBIDXXX (SUBIDXXX);

-- INICIA EN 100 POR CADA SUBPARTIDA,SECUENCIA DE DESDOBLAMIENTO sera realizado por desarrollo
