
ALTER TABLE SIAI0207
ADD COLUMN  `DVANRADX` varchar(50) NOT NULL COMMENT 'Numero Radicado';


  ALTER TABLE SIAI0207
 ADD COLUMN `DVAFHRAD` datetime NOT NULL COMMENT 'Fecha y Hora Radicado';
 
 
  ALTER TABLE SIAI0207
  ADD COLUMN `DVAESTCA` varchar(20) NOT NULL COMMENT 'Estado Consumo API';
   
   ALTER TABLE SIAI0207
   ADD COLUMN`DVARESCA` text NOT NULL COMMENT 'Resultado Consumo API';