-- TABLA APOU0003-APPLE- CABECERA 214 Y DETALLE LX 214 VS DETALLE AT7 y MS1

CREATE TABLE APOU0003(

DOCNROOX VARCHAR(15) NOT NULL COMMENT 'NUMERO DEL DO',
C214IDXX VARCHAR(9) NOT NULL COMMENT 'ID del consecutivo de la transaccion ST.ST02 y SE.SE02',
D214IDXX INT(6) NOT NULL COMMENT 'ID de la secuencia LX.LX01',
D214SSCX ENUM('','K1','X6') NOT NULL COMMENT 'Codigo que indica el estado del envio AT7.AT701',
D214SSRC ENUM('','NS') NOT NULL COMMENT 'Codigo del estado del envio AT7.AT701',
D21405FE DATE NOT NULL COMMENT 'AT7.AT705',
D21406TI TIME NOT NULL COMMENT 'AT7.AT706',
D21407ZO ENUM('','LT') NOT NULL COMMENT 'AT7.AT07',
D214SCNX ENUM('','BOG') NOT NULL COMMENT 'Ciudad MS1.MS101',
D214SCOC ENUM('','CO') NOT NULL COMMENT 'Pais MS1.MS103',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`DOCNROOX`, `C214IDXX`,`D214IDXX`,`D214SSCX`),
KEY idx_DOCNROXX(DOCNROOX),
KEY idx_C214IDXX(C214IDXX),
KEY idx_D214IDXX(D214IDXX)
) COMMENT = 'CABECERA 214 Y DETALLE LX 214 VS DETALLE AT7 y MS1';