-- TABLA APOU0002-APPLE- CABECERA 214 VS DETALLE LX Y AT8

CREATE TABLE APOU0002 (

DOCNROXX VARCHAR(15) NOT NULL COMMENT 'NUMERO DEL DO',
C214IDXX VARCHAR(9) NOT NULL COMMENT 'ID del consecutivo de la transaccion ST.ST02 y SE.SE02',
D214IDXX INT(6) NOT NULL COMMENT 'ID de la secuencia siempre inicia en 1 por cada cabecera LX.LX01',
D214AT84 INT(8) NOT NULL COMMENT 'Numero de unidades AT8.AT804',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`DOCNROXX`, `C214IDXX`,`D214IDXX`),
KEY idx_DOCNROXX(DOCNROXX),
KEY idx_C214IDXX(C214IDXX)
) COMMENT = 'CABECERA 214 VS DETALLE LX Y AT8';
