-- TABLA APOU0004-APPLE- CABECERA 214 Y DETALLE LX 214 VS DETALLE L11

CREATE TABLE APOU0004 (

DOCNROXX VARCHAR(15) NOT NULL COMMENT 'NUMERO DEL DO',
C214IDXX VARCHAR(9) NOT NULL COMMENT 'ID del consecutivo de la transaccion ST.STO2 y SE.SE02',
D214IDXX INT(6) NOT NULL COMMENT 'ID de la secuencial LX.LX01',
INSTRUID VARCHAR(3) NOT NULL COMMENT 'ID de la instruccion LOOP 205 L11-L1.1102 Valores sacados de la documentacion',
D214VALX TINYTEXT NOT NULL COMMENT 'Valor del detalle LOOP 205 L11.L1101',
D214FRED VARCHAR(80) NOT NULL COMMENT 'Texto para clarificar elementos del contenido LOOP 205 L11.L1103',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`DOCNROXX`, `C214IDXX`,`D214IDXX`,`INSTRUID`),
KEY idx_DOCNROXX (DOCNROXX),
KEY idx_C214IDXX (C214IDXX),
KEY idx_D214IDXX (D214IDXX),
KEY idx_INSTRUID (INSTRUID)
) COMMENT = 'CABECERA 214 Y DETALLE LX 214 VS DETALLE L11';