-- TABLA HPIN0002 - HP - CUSDEC IMPORT DECLARATION

CREATE TABLE HPIN0002 (
    CUSIDXXX INT(6)  NOT NULL COMMENT 'Indica el ID del cusdec header',
    CUIMIDXX VARCHAR(35) NOT NULL COMMENT 'Consecutivo interno de HP (ImportDeclaration.ID)',
    CUIMORNU SMALLINT(3) NOT NULL COMMENT 'Atributo de la etiqueta ImportDeclaration.ChangeOrdinalNumberValue',
    CUIMAUID TINYTEXT NOT NULL COMMENT 'Identificador de la importación asignado por la entidad autorizada (ImportDeclaration.CustomsAuthorityImportDeclarationID)',
    CUIMCUBR TINYTEXT NOT NULL COMMENT 'Identificador del agente de aduanas (ImportDeclaration.CustomsBrokerReferenceID)',
    CUIMCRBT TINYTEXT NOT NULL COMMENT 'Identificador del modo de transporte (ImportDeclaration.CrossBorderTransportMeansID)',
    CUIMCBJI TINYTEXT NOT NULL COMMENT 'Identificador del viaje (ImportDeclaration.CrossBorderJourneyID)',
    CUIMINTM TINYTEXT NOT NULL COMMENT 'Medio de transporte desde país de compra a oficina de aduana (ImportDeclaration.InlandTransportMeansID)',
    CUIMIMTY VARCHAR(5) NOT NULL COMMENT 'Código del tipo de importación (ImportDeclaration.ImportTypeCode)',
    CUIMIMDT VARCHAR(5) NOT NULL COMMENT 'Código del tipo de importación para la declaración (ImportDeclaration.ImportDeclarationTypeCode)',
    CUIMCACC VARCHAR(3) NOT NULL COMMENT 'Código del país a la que se envía el mensaje (ImportDeclaration.CustomsAuthorityCountryCode)',
    CUIMEXCC VARCHAR(3) NOT NULL COMMENT 'Código del país donde se exportan los bienes (ImportDeclaration.ExportingCountryCode)',
    CUIMDECC VARCHAR(3) NOT NULL COMMENT 'Código del país donde se importa (ImportDeclaration.DestinationCountryCode)',
    CUIMDERC VARCHAR(6) NOT NULL COMMENT 'Código de la región donde se importa (ImportDeclaration.DestinationRegionCode)',
    CUIMIPRC VARCHAR(6) NOT NULL COMMENT 'Código de las partes involucradas en la importación (ImportDeclaration.ImportPartyRepresentationCode)',
    CUIMCBTC VARCHAR(2) NOT NULL COMMENT 'Código modo de transporte cruzando frontera (ImportDeclaration.CrossBorderTransportModeCode)',
    CUIMBTTC VARCHAR(3) NOT NULL COMMENT 'Código tipo de transporte cruzando frontera (ImportDeclaration.CrossBorderTransportMeansTypeCode)',
    CUIMBTDS TINYTEXT NOT NULL COMMENT 'Descripción del tipo de transporte cruzando frontera (ImportDeclaration.CrossBorderTransportMeansDescription)',
    CUIMTMNC VARCHAR(3) NOT NULL COMMENT 'Nacionalidad del medio de transporte usado, a través de la frontera (ImportDeclaration.CrossBorderTransportMeansNationalityCountryCode)',
    CUIMITMC VARCHAR(2) NOT NULL COMMENT 'Modo de transporte dentro del país de importación (ImportDeclaration.InlandTransportModeCode)',
    CUIMINCC VARCHAR(3) NOT NULL COMMENT 'Nacionalidad del transporte dentro del país de importación (ImportDeclaration.InlandTransportMeansNationalityCountryCode)',
    CUIMITTC VARCHAR(2) NOT NULL COMMENT 'Código del tipo de transacción subyacente asociado a la importación (ImportDeclaration.ImportBusinessTransactionTypeCode)',
    CUIMCDDT VARCHAR(20) NOT NULL COMMENT 'Cancelación de la importación, fecha de creación de la declaración (ImportDeclaration.CancellationRequestIndicator.DeclarationDateTime)',
    CUIMCDDZ VARCHAR(10) NOT NULL COMMENT 'Atributo código de la zona horaria (ImportDeclaration.CancellationRequestIndicator.DeclarationDateTime)',
    CUIMCDDD VARCHAR(10) NOT NULL COMMENT 'Atributo hora de verano (ImportDeclaration.CancellationRequestIndicator.DeclarationDateTime)',
    CUIMCDIT VARCHAR(3) NOT NULL COMMENT 'Código de representación del incoterms (ImportDeclaration.Incoterms.ClassificationCode)',
    CUIMITLN TINYTEXT NOT NULL COMMENT 'Lugar donde aplica el incoterm (ImportDeclaration.Incoterms.TransferLocationName)',
    CUIMLLNV INT(9) NOT NULL COMMENT 'Número total de listas de importación (ImportDeclaration.LoadingListNumberValue)',
    CUIMTPNV INT(9) NOT NULL COMMENT 'Número total de paquetes de importación (ImportDeclaration.TotalPackageNumberValue)',
    CUIMTGWQ INT(9) NOT NULL COMMENT 'Número total de peso bruto de importación (ImportDeclaration.TotalGrossWeightQuantity)',
    CUIMTGWU VARCHAR(3) NOT NULL COMMENT 'Unidad de medida del peso bruto de importación atributo unitCode (ImportDeclaration.TotalGrossWeightQuantity)',
    CUIMTNWQ INT(9) NOT NULL COMMENT 'Número total de peso neto de importación (ImportDeclaration.TotalNetWeightQuantity)',
    CUIMTNWU VARCHAR(3) NOT NULL COMMENT 'Unidad de medida del peso neto de importación atributo unitCode (ImportDeclaration.TotalNetWeightQuantity)',

    PRIMARY KEY (`CUSIDXXX `, `CUIMIDXX`),
    KEY idx_CUSIDXXX (CUSIDXXX)

) COMMENT = 'CUSDEC IMPORT DECLARATION';
