
-- TABLA HPIN0007 - HP - CUSDEC IMPORT DECLARATION, CONTAINERS VS SEALS

CREATE TABLE HPIN0007 (
    CUSIDXXX INT(6) NOT NULL COMMENT 'Indica el ID del cusdec header',
    CUIMIDXX VARCHAR(35) NOT NULL COMMENT 'Consecutivo interno de HP (ImportDeclaration.ID)',
    CUIMCOID VARCHAR(35) NOT NULL COMMENT 'Identificador del contenedor (ImportDeclaration.Container.ID)',
    CIIMSEID VARCHAR(35) NOT NULL COMMENT 'Identificador del sello (ImportDeclaration.Container.Seal.ID)',

    PRIMARY KEY (`CUSIDXXX`, `CUIMIDXX`, `CUIMCOID`, `CIIMSEID`),
    KEY idx_CUSIDXXX (CUSIDXXX),
    KEY idx_CUIMIDXX (CUIMIDXX)
) COMMENT = 'CUSDEC IMPORT DECLARATION, CONTAINERS VS SEALS';


