
CREATE TABLE HPO12025 (

HPOCIDXX BIGINT NOT NULL COMMENT 'ID de la cabecera,siempre inicia con el año',
HPOIIDXX VARCHAR(35) NOT NULL COMMENT 'Identificador de la importacion (importDeclaration.ID)',
HPOJIDXX SMALLINT NOT NULL COMMENT 'Identificador de la secuencia del texto natural, por cada HPOCIDXX y HPOIIDXX',
HPO1IDXX SMALLINT NOT NULL COMMENT 'IDENTIFICADOR DEL CONTENEDOR ASIGNADO, POR CADA HPOCIDXX,HPOIIDXX Y HPOJIDXX',
HPO1COID VARCHAR(35) NOT NULL COMMENT 'IDENTIFICADOR DEL CONTENEDOR (importDeclaration.Item.containerAssingnment.containerID)',
HPO1PRQU DECIMAL(14,8) NOT NULL COMMENT 'cantidad del producto (importDeclaration.Item.containerAssingnment.productQuantity)',
HPO1PRQC VARCHAR(3) NOT NULL COMMENT 'atributo unitCode,cantidad del producto(importDeclaration.Item.containerAssingnment.productQuantity)',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`HPOCIDXX`,`HPOIIDXX`,`HPOJIDXX`,`HPO1IDXX`),
KEY IDX_HPOCIDXX(HPOCIDXX),
KEY IDX_HPOIIDXX(HPOIIDXX),
KEY IDX_HPOJIDXX(HPOJIDXX)

) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT'CUSRES HEADER,IMPORT DECLARATION ITEM VS CONTAINER ASSIGNMENT'