CREATE TABLE HPOF2025 (
    HPOCIDXX BIGINT(12) NOT NULL COMMENT 'ID de la cabecera, siempre inicia con el año (MessageHeader.ID)',
    HPOIIDXX VARCHAR(35) NOT NULL COMMENT 'Identificador de la importación (ImportDeclaration.ID)',
    HPOGIDXX SMALLINT NOT NULL COMMENT 'Identificador de la secuencia de la autoridad',
    HPOFIDXX SMALLINT NOT NULL COMMENT 'Identificador de la secuencia del status, por cada HPOCIDXX, HPOIIDXX y HPOGIDXX debe iniciar en 100 e incrementar',
    HPOFCOXX VARCHAR(6) NOT NULL COMMENT 'Código de representación del progreso de la importación (ImportDeclaration.GovernmentAuthority.ProcessingStatus.Code)',
    HPOFCODE TINYTEXT NOT NULL COMMENT 'Descripción del código (ImportDeclaration.GovernmentAuthority.ProcessingStatus.CodeDescription)',
    HPOFEFDA DATETIME NOT NULL COMMENT 'Fecha cuando sucedió el evento (ImportDeclaration.GovernmentAuthority.ProcessingStatus.EffectiveDateTime)',
    HPOFEFTZ VARCHAR(10) NOT NULL COMMENT 'Atributo timeZoneCode de la fecha cuando sucedió el evento (ImportDeclaration.GovernmentAuthority.ProcessingStatus.EffectiveDateTime)',
    HPOFEFTI VARCHAR(5) NOT NULL COMMENT 'Atributo daylightSavingTimeIndiCator de la fecha cuando sucedioel evento(ImportDeclaration.GovernmentAuthority.ProcessingStatus.EffectiveDateTime)',
    REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
    REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
    REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
    REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
    REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
    REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
    REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
    REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
   PRIMARY KEY (`HPOCIDXX`,`HPOIIDXX`,`HPOGIDXX`,`HPOFIDXX`),
   KEY IDX_HPOCIDXX(HPOCIDXX),
   KEY IDX_HPOIIDXX(HPOIIDXX),
   KEY IDX_HPOGIDXX(HPOGIDXX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'CUSRES HEADER, IMPORT DECLARATION, GOVERNMENT AUTHORITY VS PROCESSING STATUS';
