CREATE TABLE `HPOJ2025` (
  `HPOCIDXX` BIGINT(12) NOT NULL COMMENT 'ID de la cabecera, siempre inicia con el año (MessageHeader.ID)',
  `HPOIIDXX` VARCHAR(35) NOT NULL COMMENT 'Identificador de la importación (ImportDeclaration.ID)',
  `HPOIJDXX` SMALLINT NOT NULL COMMENT 'Identificador de la secuencia del texto natural, por cada HPOCIDXX y HPOIIDXX ',
  `HPOJIDID` VARCHAR(10) NOT NULL COMMENT 'Identificador del ítem en la importación (ImportDeclaration.Item.ID)',
  `HPOJITID` VARCHAR(10) NOT NULL COMMENT 'Identificador de la importación en el ítem (ImportDeclaration.Item.CustomsAuthorityImportDeclarationItemID)',
  `HPOJVESE` VARCHAR(32) COMMENT 'Identificador del vehículo (ImportDeclaration.Item.VehicleSerialID)',  
  `HPOJCCCL` VARCHAR(17) COMMENT 'Código de la clasificación en la declaración de importación (ImportDeclaration.Item.CustomsCommodityClassificationCode)',
  `HPOJCUPR` VARCHAR(8) COMMENT 'Código del régimen (ImportDeclaration.Item.CustomsProcedureCode)',
  `HPOJCAPC` VARCHAR(4) COMMENT 'Código adicional del régimen (ImportDeclaration.Item.CustomsAdditionalProcedureCode)',
  `HPOJCTMC` VARCHAR(4) COMMENT 'Adicionales al régimen (ImportDeclaration.Item.CustomsTariffMeasureAdditionalCode)',
  `HPOJCTCC` VARCHAR(5) COMMENT 'Código de presentación de la tarifa (ImportDeclaration.Item.CustomsTariffConcessionCode)',
  `HPOJEXCO` VARCHAR(3) COMMENT 'Código del país que exportó (ImportDeclaration.Item.ExportingCountryCode)',
  `HPOJDECO` VARCHAR(3) COMMENT 'Código del país de destino (ImportDeclaration.Item.DestinationCountryCode)',
  `HPOJORCO` VARCHAR(3) COMMENT 'Código del país de origen (ImportDeclaration.Item.OriginCountryCode)',
  `HPOJRECO` VARCHAR(6) COMMENT 'Código de la región de origen (ImportDeclaration.Item.OriginRegionCode)',
  `HPOJREDA` DATETIME COMMENT 'Fecha de llegada (ImportDeclaration.Item.ReleaseDateTime)',
  `HPOJRETZ` VARCHAR(10) COMMENT 'Atributo TimeZoneCode, fecha de llegada (ImportDeclaration.Item.ReleaseDateTime)',
  `HPOJREDS` VARCHAR(5) COMMENT 'Atributo DaylightSavingTimeIndicator, fecha de llegada (ImportDeclaration.Item.ReleaseDateTime)',
  `HPOJDESX` TINYTEXT COMMENT 'Descripción del ítem (ImportDeclaration.Item.Description)',
  `HPOJQUAN` DECIMAL(17,14) COMMENT 'Cantidad del ítem (ImportDeclaration.Item.Quantity)',
  `HPOJQUAU` VARCHAR(3) COMMENT 'Atributo unitCode, cantidad del ítem (ImportDeclaration.Item.Quantity)',
  `HPOJFCQU` DECIMAL(17,14) COMMENT 'Primera cantidad del ítem (ImportDeclaration.Item.FirstCustomsSupplementaryQuantity)',
  `HPOJFCQN` VARCHAR(5) COMMENT 'Atributo unitCode, primera cantidad del ítem (ImportDeclaration.Item.FirstCustomsSupplementaryQuantity)',
  `HPOJSCQU` DECIMAL(17,14) COMMENT 'Segunda cantidad del ítem (ImportDeclaration.Item.SecondCustomsSupplementaryQuantity)',
  `HPOJSCQN` VARCHAR(5) COMMENT 'Atributo unitCode, segunda cantidad del ítem (ImportDeclaration.Item.SecondCustomsSupplementaryQuantity)',
  `HPOJGWQA` DECIMAL(17,14) COMMENT 'Peso bruto del ítem (ImportDeclaration.Item.GrossWeightQuantity)',
  `HPOJGWQU` VARCHAR(3) COMMENT 'Atributo unitCode, peso bruto del ítem (ImportDeclaration.Item.GrossWeightQuantity)',
  `HPOJNEWE` DECIMAL(17,14) COMMENT 'Peso neto del ítem (ImportDeclaration.Item.NetWeightQuantity)',
  `HPOJNEWU` VARCHAR(3) COMMENT 'Atributo unitCode, peso neto del ítem (ImportDeclaration.Item.NetWeightQuantity)',
  `HPOJPRID` VARCHAR(60) COMMENT 'Identificador del producto enviado en el master data (ImportDeclaration.Item.InternalID)',
   REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
   REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
   REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
   REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
   REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
   REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
   REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
   REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado', 

 
  PRIMARY KEY (`HPOCIDXX`, `HPOIIDXX`, `HPOIJDXX`),
  KEY IDX_HPOCIDXX(HPOCIDXX),
  KEY IDX_HPOIIDXX(HPOIIDXX) 
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT='CUSRES HEADER, IMPORT DECLARATION VS ITEM';

 ALTER TABLE `HPOJ2025`
CHANGE COLUMN `HPOIJDXX` `HPOJIDXX` SMALLINT NOT NULL COMMENT 'Identificador de la secuencia del texto natural, por cada HPOCIDXX y HPOIIDXX ';