CREATE TABLE HPOX2025 (
    HPOCIDXX BIGINT(12) NOT NULL COMMENT 'ID de la cabecera, siempre inicia con el año (MessageHeader.ID)',
    HPOIIDXX VARCHAR(35) NOT NULL COMMENT 'Identificador de la importación (ImportDeclaration.ID)',
    HPOJIDXX SMALLINT NOT NULL COMMENT 'Identificador de la secuencia del texto natural, por cada HPOCIDXX y HPOIIDXX',
    HPOXIDXX SMALLINT NOT NULL COMMENT 'Identificador del Exporter Party, por cada HPOCIDXX, HPOIIDXX y HPOJIDXX, inicia en 100',
    HPOXSTID VARCHAR(60) COMMENT 'Identificador de la agencia exportadora (ImportDeclaration.Item.ExporterParty.StandardID)',
    HPOXSCAG VARCHAR(60) COMMENT 'Atributo schemeAgencyID, identificador de la agencia exportadora (ImportDeclaration.Item.ExporterParty.StandardID.schemeAgencyID)',
    HPOXINID VARCHAR(32) COMMENT 'Identificador del exportador (ImportDeclaration.Item.ExporterParty.InternalID)',
    HPOXTXID VARCHAR(20) COMMENT 'Identificador de impuesto (ImportDeclaration.Item.ExporterParty.TaxID)',
    HPOXAOFN VARCHAR(40) COMMENT 'Nombre de la organización que representa (ImportDeclaration.Item.ExporterParty.Address.OrganisationFormattedName)',
    HPOXAPCO VARCHAR(3) COMMENT 'Código del país (ImportDeclaration.Item.ExporterParty.Address.PhysicalAddress.CountryCode)',
    HPOXAPRC VARCHAR(6) COMMENT 'Código de la región (ImportDeclaration.Item.ExporterParty.Address.PhysicalAddress.RegionCode)',
    HPOXAPSC VARCHAR(10) COMMENT 'Código postal (ImportDeclaration.Item.ExporterParty.Address.PhysicalAddress.StreetPostalCode)',
    HPOXAPCN VARCHAR(40) COMMENT 'Nombre de la ciudad (ImportDeclaration.Item.ExporterParty.Address.PhysicalAddress.CityName)',
    HPOXAACN VARCHAR(40) COMMENT 'Nombre adicional de la ciudad (ImportDeclaration.Item.ExporterParty.Address.PhysicalAddress.AdditionalCityName)',
    HPOXAASN VARCHAR(60) COMMENT 'Dirección (ImportDeclaration.Item.ExporterParty.Address.PhysicalAddress.StreetName)',
    REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario creación del registro',
    REGFECXX DATE NOT NULL COMMENT 'Fecha de creación del registro',
    REGHORXX TIME NOT NULL COMMENT 'Hora de creación del registro',
    REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de modificación',
    REGFECMX DATE NOT NULL COMMENT 'Fecha de modificación del registro',
    REGHORMX TIME NOT NULL COMMENT 'Hora de modificación del registro',
    REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del registro',
    REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Última modificación',
    
    PRIMARY KEY (`HPOCIDXX`, `HPOIIDXX`,`HPOJIDXX`,`HPOXIDXX`),
    KEY IDX_HPOCIDXX (HPOCIDXX),
    KEY IDX_HPOIIDXX (HPOIIDXX),
    KEY IDX_HPOJIDXX (HPOJIDXX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'CUSRES HEADER, IMPORT DECLARATION ITEM VS EXPORTER PARTY';
