CREATE TABLE  `MDCP2025` (
  `CLIIDXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cliente',
  `PIEIDXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Proveedor',
  `PROIDXXX` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Producto',
  `FACIDXXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Factura',
  `PRODESFA` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Descripcion segun factura',
  `DOCSERSE` tinytext COLLATE utf8_unicode_ci NOT NULL COMMENT 'Respuesta servicio',
  `REGUSRXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion',
  `REGESTXX` enum('ACTIVO','INACTIVO','FALLIDO') COLLATE utf8_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp',
  PRIMARY KEY (`CLIIDXXX`,`PIEIDXXX`,`PROIDXXX`,`FACIDXXX`),
  KEY IDX_CLIIDXXX(CLIIDXXX),
  KEY IDX_PIEIDXXX(PIEIDXXX),
  KEY IDX_PROIDXXX(PROIDXXX)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=COMPACT COMMENT='Productos vs Agendamiento de Cadena de Distribucion de Datos';
