CREATE TABLE DTRO2024 (

DTRCDOTR VARCHAR(50) NOT NULL COMMENT'Numero de Documento de Transporte (UK) (DTRCYYYY)' ,
DTRCNICO VARCHAR(50) NOT NULL COMMENT'NIT Consignatario (CIPO0024)',
IDARCHXX INT(10) NOT NULL COMMENT'ID del archivo (DOCCYYYY)',
COTIDXXX SMALLINT NOT NULL COMMENT'ID DEL CONTROLADOR (CIMS0072)',
USRIDXXX VARCHAR(15) NOT NULL COMMENT'ID del usuario(CIMS0001)',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`DTRCDOTR`, `DTRCNICO`,`IDARCHXX`, `COTIDXXX`,`USRIDXXX`),
KEY IDX_DTRCDOTR(DTRCDOTR),
KEY IDX_DTRCNICO(DTRCNICO),
KEY IDX_IDARCHXX(IDARCHXX),
KEY IDX_COTIDXXX(COTIDXXX)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT'documento de transporte vs controladores'
