CREATE TABLE RDLC2024(

MDREIDRE INT NOT NULL COMMENT 'Secuencia del registro o Licencia',
PROIDXXX VARCHAR(20) NOT NULL COMMENT 'Codigo del producto',
CLIIDXXX VARCHAR(20) NOT NULL COMMENT 'Nit del Cliente',
IDPROXXX VARCHAR(10) NOT NULL COMMENT 'ID del proveedor (CIPO0050)',
RESIDXXX INT NOT NULL COMMENT 'ID de la restriccion (CIPO0035)',
EMPNITXX VARCHAR(20) NOT NULL COMMENT 'Nit de la empresa',
AREAIDXX INT NOT NULL COMMENT 'ID del area',
SERIEIDX INT NOT NULL COMMENT 'ID de la serie',
TIPOIDXX INT NOT NULL COMMENT 'ID del Tipo',
IDARCHXX BIGINT NOT NULL COMMENT 'Archivo Genio Documental',
PRORESCR ENUM('','SI','NO') NOT NULL COMMENT 'BANDERA QUE INDICA SU CUMPLE CON LOS REQUISITOS',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`MDREIDRE`, `PROIDXXX`,`CLIIDXXX`, `IDPROXXX`,`RESIDXXX`, `EMPNITXX`,`AREAIDXX`, `SERIEIDX`,`TIPOIDXX`, `IDARCHXX`),
KEY IDX_MDREIDRE(MDREIDRE),
KEY IDX_PROIDXXX(PROIDXXX),
KEY IDX_CLIIDXXX(CLIIDXXX),
KEY IDX_IDPROXXX(IDPROXXX),
KEY IDX_RESIDXXX(RESIDXXX),
KEY IDX_EMPNITXX(EMPNITXX),
KEY IDX_AREAIDXX(AREAIDXX),
KEY IDX_SERIEIDX(SERIEIDX),
KEY IDX_TIPOIDXX(TIPOIDXX),
KEY IDX_IDARCHXX(IDARCHXX)

) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'CABECERA VUCE,PRODUCTO,RESTRICCION LEGAL DOCUMENTOS VS CUMPLIMIENTO'


