
CREATE TABLE CIPO0208 (

ENTCUPID SMALLINT(3) NOT NULL AUTO_INCREMENT COMMENT 'ID CONSECUTIVO',
ENTVISID SMALLINT(4) NOT NULL AUTO_INCREMENT COMMENT 'ID de la entidad (CIPO0010)',
CUPIDXXX SMALLINT(2) NOT NULL COMMENT'CUPO',
CUPDESXX TINYTEXT NOT NULL COMMENT 'Descripcion del cupo',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'

) AUTO_INCREMENT=100 COMMENT'ENTIDAD VS CUPOS'

  ALTER TABLE `CIPO0208`
  ADD PRIMARY KEY (`ENTCUPID`,`ENTVISID`,`CUPIDXXX`),
  ADD UNIQUE KEY `UNIQUE` (`ENTCUPID`,`ENTVISID`,`CUPIDXXX`);
