CREATE TABLE CIMS0039 (
  GRUPIDXX SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID del grupo, inicia en 100',
  GRUPDESX TINYTEXT COMMENT 'Descripción del grupo',
  GRUPLIDX VARCHAR(15) NOT NULL COMMENT 'ID del líder del grupo',
  CCOIDXXX VARCHAR(3) NOT NULL COMMENT 'ID del centro de costo',
  SUBCCOID VARCHAR(3) NOT NULL COMMENT 'ID del subcentro de costo',
  GRUPCLIX ENUM('NO', 'SI') NOT NULL DEFAULT 'NO' COMMENT 'Bandera que indica si el grupo atiende clientes',
  GRGRNISU SMALLINT(5) UNSIGNED COMMENT 'ID del grupo padre',
  EMAILGRU TINYTEXT COMMENT 'Email del grupo',
  SUCIDXXX VARCHAR(3) NOT NULL COMMENT 'ID de la sucursal (CIMS0050)',
  REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
  REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
  REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
  REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
  REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

  PRIMARY KEY (GRUPIDXX),
  KEY IDX_GRUPLIDXX (GRUPLIDX),
  KEY IDX_CCOIDXXX (CCOIDXXX),
  KEY IDX_SUBCCOID (SUBCCOID),
  KEY IDX_SUCIDXXX (SUCIDXXX)

) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Tabla de grupos (CIMS0039)';
