CREATE TABLE `CIMS0076` (
   COTIDXXX SMALLINT AUTO_INCREMENT PRIMARY KEY COMMENT 'CONTROLADOR VS DOCUMENTOS GENIO',
  `EMPNITXX` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Empresa Genio',
  `AREAIDXX` smallint NOT NULL COMMENT 'Proceso Genio',
  `SERIEIDX` smallint NOT NULL COMMENT 'Serie Genio',
  `TIPOIDXX` smallint NOT NULL COMMENT 'Tipo Genio',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificaion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  

  PRIMARY KEY (`COTIDXXX`),
  KEY `IDX_COTIDXXX` (`COTIDXXX`)
) AUTO_INCREMENT=100 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CONTROLADOR VS DOCUMENTOS GENIO';


ALTER TABLE CIMS0076 DROP PRIMARY KEY;  

ALTER TABLE CIMS0076 
MODIFY COLUMN COTIDXXX SMALLINT AUTO_INCREMENT PRIMARY KEY COMMENT 'CONTROLADOR VS DOCUMENTOS GENIO';

ALTER TABLE CIMS0076 
ADD UNIQUE (`EMPNITXX`, `AREAIDXX`, `SERIEIDX`, `TIPOIDXX`);


ALTER TABLE CIMS0076 AUTO_INCREMENT = 100;

SELECT AUTO_INCREMENT 
FROM information_schema.TABLES 
WHERE TABLE_NAME = 'CIMS0076' 
AND TABLE_SCHEMA = 'CIMA';



