CREATE TABLE CIMS0075 (
USRIDXXX VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del usuario',
MODIDXXX INT NOT NULL COMMENT 'ID  del modulo',
PROIDXXX INT NOT NULL COMMENT 'ID del proceso',
MENIDXXX INT NOT NULL COMMENT 'ID de la opcion de menu',
USRBANXX ENUM ('','SI','NO') NOT NULL COMMENT 'bandera que indica tiene habilitado la opcion en el banner',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`USRIDXXX`, `MODIDXXX`,`PROIDXXX`, `MENIDXXX`),
KEY IDX_USRIDXXX(USRIDXXX),
KEY IDX_MODIDXXX(MODIDXXX),
KEY IDX_PROIDXXX(PROIDXXX),
KEY IDX_MENIDXXX(MENIDXXX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT'USUARIO VS BANNER '