CREATE TABLE CIPO0216(
CLIIDXXX VARCHAR(20) NOT NULL COMMENT'Nit cliente (CIPO0024)',
IDPROXXX VARCHAR(10) NOT NULL COMMENT'ID DEL PROVEEDOR (CIPO0050)',
PROIDXXX VARCHAR(20) NOT NULL COMMENT'Codigo del Producto (CIPO0141)',
NOMBVARX VARCHAR(30) NOT NULL COMMENT'Nombre Variable (CIPO0214)',
VALDESXX TINYTEXT NOT NULL COMMENT'Valor diligenciado',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`CLIIDXXX`, `IDPROXXX`,`PROIDXXX`,`NOMBVARX`),
KEY IDX_CLIIDXXX(CLIIDXXX),
KEY IDX_IDPROXXX(IDPROXXX),
KEY IDX_PROIDXXX(PROIDXXX),
KEY IDX_NOMBVARX(NOMBVARX)

)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT'PRODUCTOS VS VARIABLES CLIENTE PROVEEDOR Y TIPO DE PRODUCTO'