CREATE TABLE CIPO0210 (

CLIIDXXX VARCHAR(20) NOT NULL COMMENT'Nit cliente (CIPO0024)',
MODIDXXX INT NOT NULL COMMENT 'ID del modulo (CIMS0003)',
PROIDXXX INT NOT NULL COMMENT 'ID del proceso (CIMS0004)',
AREAIDXX SMALLINT NOT NULL COMMENT 'ID del area',
AREADESX TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Descripcion del area de Genio',
SERIEIDX SMALLINT NOT NULL COMMENT 'ID de la serie',
SERIEDES TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Descripcion de la serie en Genio',
TIPOIDXX SMALLINT NOT NULL COMMENT 'ID del Tipo',
TIPODESX TINYTEXT NOT NULL COMMENT 'Descripcion del Tipo en Genio',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`CLIIDXXX`, `MODIDXXX`,`PROIDXXX`, `AREAIDXX`, `SERIEIDX`,`TIPOIDXX`),
KEY IDX_CLIIDXXX(CLIIDXXX),
KEY IDX_MODIDXXX(MODIDXXX),
KEY IDX_PROIDXXX(PROIDXXX)

) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'Cliente vs Documentos Genio'