CREATE TABLE CIPO0212 (

TARSECID SMALLINT NOT NULL AUTO_INCREMENT COMMENT'Secuencia de la tarifa',
TARANOXX VARCHAR(4) NOT NULL COMMENT 'Año de la tarifa',
TARINIXX DATE  NOT NULL COMMENT 'Vigencia inicial',
TARFINXX DATE NOT NULL COMMENT 'Vigencia final',
TARBCLIX ENUM ('','SI','NO') NOT NULL COMMENT'bandera que indica si aplica cliente especifico',
CLIIDXXX VARCHAR(20) NOT NULL COMMENT 'Nit cliente (CIPO0024)',
TARDESXX TINYTEXT NOT NULL COMMENT 'Descripcion de la ruta',
SUCIDXXX VARCHAR(3) NOT NULL COMMENT 'sucursal (CIMS0050)',
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`TARSECID`)
) AUTO_INCREMENT=100  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT 'TARIFA DE TRANSPORTE'