CREATE TABLE `RLPP2025` (
  `MDREIDRE` int NOT NULL COMMENT 'Secuencia del registro o LICENCIA',
  `PROIDXXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Código del producto',
  `CLIIDXXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'NIT del Cliente',
  `IDPROXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del proveedor (CIPO0050)',
  `ENTVISID` smallint NOT NULL COMMENT 'ID de la Entidad (CIPO0010)',
  `PERIDXXX` smallint NOT NULL COMMENT 'ID del Permiso (CIPO0194)',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creación del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creación del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificación',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificación del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificación del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CABECERA VUCE, PRODUCTO TIPO PERMISO VS ENTIDAD' ROW_FORMAT=COMPACT;

ALTER TABLE `RLPP2025`
  ADD PRIMARY KEY (`MDREIDRE`, `PROIDXXX`, `CLIIDXXX`, `IDPROXXX`, `ENTVISID`, `PERIDXXX`) USING BTREE,
  ADD KEY `MDREIDRE` (`MDREIDRE`) USING BTREE,
  ADD KEY `PROIDXXX` (`PROIDXXX`) USING BTREE,
  ADD KEY `CLIIDXXX` (`CLIIDXXX`) USING BTREE,
  ADD KEY `IDPROXXX` (`IDPROXXX`) USING BTREE,
  ADD KEY `ENTVISID` (`ENTVISID`) USING BTREE,
  ADD KEY `PERIDXXX` (`PERIDXXX`) USING BTREE;
