CREATE TABLE CIPO0205(

CAPSUBXX VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del capitulo',
PARSUBXX VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID de LA PARTIDA',
ARMSUBXX VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del sistema armonizado',
ANDSUBXX VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID de ANDINA',
SUBSUBXX VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ciNOT NULL COMMENT 'ID de 2 dígitos subpartida',
SUBIDXXX VARCHAR (10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT'ID de la subpartida (código arancelario)',
CAPSUBCO VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del capitulo de la correlacion',
PARSUBCO VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID de LA PARTIDA de la correlacion',
ARMSUBCO VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID del sistema armonizado de la correlacion',
ANDSUBCO VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID de ANDINA de la correlación',
SUBSUBCO VARCHAR (2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID de 2 dígitos subpartida de la correlación',
SUBIDCOX VARCHAR (10)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT  'ID de la subpartida (código arancelario) de la correlacion',
FECFINCO DATE  NOT NULL COMMENT  'Fecha de finalizacion',
JUSTCOXX TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  COMMENT 'Justificacion de la correlacion directa',

PRIMARY KEY (`CAPSUBXX`, `PARSUBXX`,`ARMSUBXX`, `ANDSUBXX`,`SUBSUBXX`, `SUBIDXXX`,`CAPSUBCO`, `PARSUBCO`,`ARMSUBCO`, `ANDSUBCO`,`SUBSUBCO`, `SUBIDCOX`),

KEY idx_CAPSUBXX(CAPSUBXX),
KEY idx_PARSUBXX(PARSUBXX),
KEY idx_ARMSUBXX(ARMSUBXX),
KEY idx_ANDSUBXX(ANDSUBXX),
KEY idx_SUBSUBXX(SUBSUBXX),
KEY idx_SUBIDXXX(SUBIDXXX)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  COMMENT 'SUBPARTIDA VS SUBPARTIDAS CON CORRELACION DIRECTA';