CREATE TABLE DSVO2025 (
    
CLIIDXXX VARCHAR(15) NOT NULL COMMENT'ID del cliente (CIPO0024)',
IDPROXXX VARCHAR(10) NOT NULL COMMENT'ID DEL PROVEEDOR (CIPO0050)',
FACIDXXX VARCHAR(50) NOT NULL COMMENT'Numero de la factura',    
COTIDXXX SMALLINT NOT NULL COMMENT 'ID DEL CONTROLADOR (CIMS0072)',
USRIDXXX VARCHAR(15) NOT NULL COMMENT'ID del usuario (CIMS0001)',    
REGUSRXX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
REGFECXX DATE NOT NULL COMMENT 'Fecha de Creacion del Registro',
REGHORXX TIME NOT NULL COMMENT 'Hora de Creacion del Registro',
REGUSRMX VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
REGFECMX DATE NOT NULL COMMENT 'Fecha de Modificacion del Registro',
REGHORMX TIME NOT NULL COMMENT 'Hora de Modificaion del Registro',
REGESTXX ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro ',
REGSTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',

PRIMARY KEY (`CLIIDXXX`, `IDPROXXX`,`FACIDXXX`, `COTIDXXX`, `USRIDXXX`),
KEY IDX_CLIIDXXX(CLIIDXXX),
KEY IDX_IDPROXXX(IDPROXXX) ,
KEY IDX_FACIDXXX(FACIDXXX) ,
KEY IDX_COTIDXXX(COTIDXXX) ,
KEY IDX_USRIDXXX(USRIDXXX)    
    
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT'CABECERA DE SALDO DE FACTURA VS CONTROLADORES '