CREATE TABLE `CIPF0045` (
  `VARFINID` int NOT NULL COMMENT 'ID de la variable financiera',
  `VARFIDES` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DESCRIPCION DE LA VARIABLE',
  `VARFIVAL` decimal(20,3) NOT NULL COMMENT 'VALOR DE LA VARIABLE',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='VARIABLES FINANCIERAS' ROW_FORMAT=DYNAMIC;


ALTER TABLE CIPF0045 
ADD COLUMN VARANIOX VARCHAR(4) NOT NULL DEFAULT '' COMMENT 'Año de la vigencia';


ALTER TABLE CIPF0045 
ADD COLUMN VARNOMAQ VARCHAR(20) NOT NULL DEFAULT '' COMMENT 'Nombre maquina';

ALTER TABLE CIPF0045
MODIFY COLUMN VARFIVAL decimal(12,3) NOT NULL COMMENT 'VALOR DE LA VARIABLE';


