CREATE TABLE `CIPF0032` (
  `CLIIDXXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Nit cliente',
  `CLITIPFA` enum('','POR OPERACION','CONSOLIDADA') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'indica el tipo de facturacion',
  `CLICONFA` enum('','FACTURAR SIEMPRE AL ALIADO','FACTURAR SIEMPRE AL CLIENTE','PREGUNTAR POR OPERACION') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CONDICION DE FACTURACION ALIADO',
  `CLISEPLI` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI LA FACTURA SE DEBE SEPARAR POR LINEA DE NEGOCIO',
  `CLIIPPPC` enum('','CONSOLIDARIP','SEPARARIP') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SISE DEBE CONSOLIDAD IP + PPC O MANEJARLOSSEPARADOS',
  `CLICONPP` enum('','MOSTRARFACTURAIPPPC','MOSTRARIPCERTIFICADO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI SEDEBE MOSTRAR IP PPC POR FACTURA O MOSTRAR IP PPCY CERTIFICADO DE REINTEGRO A CAPITAL',
  `CLISEPPP` enum('','GENFACIP','GENFACIPCER') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI SE DEBE SEPARAR IP PPC POR FACTURA O MOSTRAR IP PPC Y CERTIFICADO DE REINTEGRO A CAPITAL',
  `CLIOTRTV` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI TIENE OTRAS CONDICIONES TARIFA VARIABLE POR VOLUMEN DE OPERACION',
  `CLIOTRAP` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI APLICA PRE FACTURA',
  `CLIOTRAR` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI APLICA REPORTE PARA ENVIO DE PREFACTURA',
  `CLIOTRSP` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI APLICA ENVIO DE SOPORTES PRE FACTURA',
  `CLIOTRAS` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI APLICA ENVIO DE SOPORTES FACTURA',
  `CLIPERXX` enum('','SEMANAL','MENSUAL','MANUAL') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'INDICA LA PERIODICIDAD DE LA FACTURACION',
  `CLIPERSE` enum('','LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'INDICA LA PERIODICIDAD DE LA FACTURACION',
  `CLIPERSH` time NOT NULL COMMENT 'HORA DE ENVIO',
  `CLIPERME` enum('','DIA FIJO','FECHA FIJA') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA COMO SE PARAMETRIZA LA FECHA MENSUAL',
  `CLIPERMS` enum('','LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'INDICA EL DIA DE LA FACTURACION CUANDO ES DIA DE LA SEMANA FIJO FACTURACION',
  `CLIPERMC` enum('','PRIMER','SEGUNDO','TERCERO','CUARTO','ULTIMO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'INDICA LA LOGICA DE QUE DIA DE LA SEMANA FIJO FACTURACION',
  `CLIPERMH` time NOT NULL COMMENT 'HORA DE ENVIO PARA DIA DE LA SEMANA FIJO',
  `CLIPERFE` int NOT NULL COMMENT 'indica el dia del mes en fecha fija',
  `CLIPERFH` time NOT NULL COMMENT 'HORA DE ENVIO PARA DIA DE LA fecha fija',
  `CLICONRI` enum('','COBRAR PRIMER DO','FACTURA CONSOLIDADA RIM','COBRAR EN DO DE RIM') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'bandera que indica la condicion para el cobro rim',
  `CLIPERRI` enum('','SEMANAL','MENSUAL','MANUAL') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'INDICA LA PERIODICIDAD DE LA FACTURACION RIM',
  `CLISEMRI` enum('','LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'INDICA LA PERIODICIDAD DE LA FACTURACION',
  `CLIHORRI` time NOT NULL COMMENT 'HORA DE ENVIO RIM',
  `CLIFERIM` enum('','DIA FIJO','FECHA FIJA') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA COMO SE PARAMETRIZA LA FECHA MENSUAL RIM',
  `CLIMSRIM` enum('','LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'INDICA EL DIA DE LA FACTURACION CUANDO ES DIA DE LA SEMANA FIJO FACTURACION RIM',
  `CLIDIRIM` enum('','PRIMER','SEGUNDO','TERCERO','CUARTO','ULTIMO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'INDICA LA LOGICA DE QUE DIA DE LA SEMANA FIJO FACTURACION RIM',
  `CLIHRERI` time NOT NULL COMMENT 'HORA DE ENVIO PARA DIA DE LA SEMANA FIJO RIM',
  `CLIHERIM` int NOT NULL COMMENT 'indica el dia del mes en fecha fija RIM',
  `CLIHFRIM` time NOT NULL COMMENT 'HORA DE ENVIO PARA DIA DE LA fecha fija RIM',
  `CLIRESTR` enum('','CLIENTE','SIACO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'responsable de pagos a tributos',
  `CLIFCUSD` enum('','NO','SI') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Indica si se factura en Dolares',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='cliente vs condiciones de facturacion' ROW_FORMAT=DYNAMIC;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `CIPF0032`
--
ALTER TABLE `CIPF0032`
  ADD PRIMARY KEY (`CLIIDXXX`) USING BTREE,
  ADD KEY `CLIIDXXX` (`CLIIDXXX`) USING BTREE;
COMMIT;



/* ACTUALIZACION DICCIONARIO AGREGAR COLUMNA CLIFODIV */

ALTER TABLE `CIPF0032`
ADD COLUMN CLIFODIV ENUM('','TODO EL ALIADO','INGRESOS PROPIOS AL ALIADO Y PAGOS A TERCEROS AL CLIENTE','INGRESOS PROPIOS AL CLIENTE Y PAGOS A TERCEROS AL ALIADO') NOT NULL COMMENT 'Forma division de la factura del aliado'
AFTER CLIFCUSD

