

CREATE TABLE IF NOT EXISTS `BSCC2025` (
  `USRIDXXX` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'ID USUARIO',
  `USRPERIN` date NOT NULL COMMENT 'FECHA INICIAL PERIODO',
  `USRPERFN` date NOT NULL COMMENT 'FECHA FINAL PERIODO',
  `USRMONXX` int NOT NULL COMMENT 'VALOR DEL MONTO AL GASTO',
  `USRMONCA` int NOT NULL COMMENT 'VALOR DE CAPACITACION',
  `USRUSOXX` int NOT NULL COMMENT 'VALOR USO DEL SISTEMA',
  `USRCANDE` int NOT NULL COMMENT 'CANTIDAD DE DECLARACIONES',
  `USRPORXX` decimal(5,2) NOT NULL COMMENT 'Porcetaje total por usuario',
  `USRRESXX` int NOT NULL COMMENT 'Peso Total',
  `TOTFACTX` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'DINERO TOTAL FACTURADO',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp',
  PRIMARY KEY (`USRIDXXX`,`USRPERIN`,`USRPERFN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci COMMENT='Cabecera del score card por usuario';

