
CREATE TABLE IF NOT EXISTS `DSVD2025` (
  `CLIIDXXX` varchar(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Id del cliente',
  `IDPROXXX` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Proveedor',
  `FACIDXXX` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Numero de la factura',
  `SECITEXX` int NOT NULL COMMENT 'Secuencia del Item',
  `SECITE2X` int NOT NULL COMMENT 'Secuencia 2 del Item',
  `PROIDXXX` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Codigo del producto',
  `PROID2XX` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'codigo de producto dos',
  `PRODESFA` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Descripcion segun factura',
  `SUBIDSUG` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Subpartida sugerida',
  `PAIDORXX` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Id del pais',
  `ESTMERXX` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Estado de la mercancia',
  `CODESTID` int NOT NULL COMMENT 'Id del estado de la mercancia',
  `ANIOFABX` int NOT NULL COMMENT 'Año de fabricacion',
  `FPIIDXXX` varchar(2) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Codigo forma de pago',
  `CANDAVXX` int NOT NULL COMMENT 'Cantidad Dav',
  `UNIIDXXX` int NOT NULL COMMENT 'Id de la unidad',
  `CANITEXX` int NOT NULL COMMENT 'Cantidad',
  `VALUNIIT` decimal(10,5) NOT NULL COMMENT 'Valor unitario',
  `VALTOTIT` decimal(10,5) NOT NULL COMMENT 'Valor total',
  `PESBRUIT` decimal(10,5) NOT NULL COMMENT 'Peso bruto',
  `PESNETIT` decimal(10,5) NOT NULL COMMENT 'Peso neto',
  `ORDCOMIT` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Orden de compra',
  `PEDITEXX` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Pedido del item',
  `FOBGASIT` decimal(10,5) NOT NULL COMMENT 'Valor fob Gastos facturados',
  `FLEGASIT` decimal(10,5) NOT NULL COMMENT 'Valor flete gastos facturados',
  `CONGASIT` decimal(10,5) NOT NULL COMMENT 'valor conexos Gastos facturados',
  `SEGGASIT` decimal(10,5) NOT NULL COMMENT 'Valor seguro Gastos facturados',
  `VARGASIT` decimal(10,5) NOT NULL COMMENT 'Valor varios Gastos facturados',
  `NOMCOMIT` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Nombre comercial',
  `MARCOMIT` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Marca',
  `TIPITEXX` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Tipo',
  `CLAITEXX` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Clase',
  `MODITEXX` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Modelo',
  `REFITEXX` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Referencia',
  `OTRITEXX` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Otras caracteristicas',
  `BATNUMXX` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Batch Number',
  `INFADIIT` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Informacion adicional del item',
  `DELNOTIT` tinytext CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Delivery Note',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion',
  `REGESTXX` enum('PENDIENTE','ENVIADO','PROCESADO','ERROR','INACTIVO') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT 'Bandera de Estado',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Timestamp',
  PRIMARY KEY (`CLIIDXXX`,`IDPROXXX`,`FACIDXXX`,`SECITEXX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci ROW_FORMAT=COMPACT COMMENT='Detalle Saldo de Factura';

