-- Base de datos: `CIMATEST`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `FOCP2024`
--


CREATE TABLE `FOCP2024` (
  `FOCOIDXX` int NOT NULL COMMENT 'ID DE LA OFERTA',
  `FOCOVERX` decimal(4,1) NOT NULL COMMENT 'VERSION DEL ARCHIVO ',
  `FOCPFOPA` enum('','CREDITO','CONTADO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'FORMA DE PAGO',
  `FOCPPLIN` int NOT NULL COMMENT 'PLAZO INGRESOS PROPIOS',
  `FOCPPLTE` int NOT NULL COMMENT 'PLAZO PAGOS A TERCEROS',
  `FOCPTIAN` enum('','ANTICIPO GLOBAL','POR OPERACION','SIN ANTICIPO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CONDICION DEL ANTICIPO',
  `FOCPALCU` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI APLICA CUPO',
  `FOCPTICU` enum('','LIMITADO','ILIMITADO','SIN CUPO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'TIPO DE CUPO',
  `FOCPCUTO` decimal(12,0) NOT NULL COMMENT 'CUPO TOTAL',
  `FOCPCUOP` decimal(12,0) NOT NULL COMMENT 'CUPO POR OPERACION',
  `FOCPRETR` enum('','SIACO','CLIENTE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'RESPONSABILIDAD PAGO DE TRIBUTOS',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OFERTA COMERCIAL,CONDICIONES DE PAGO' ROW_FORMAT=DYNAMIC;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `FOCP2024`
--
ALTER TABLE `FOCP2024`
  ADD PRIMARY KEY (`FOCOIDXX`,`FOCOVERX`) USING BTREE,
  ADD KEY `FOCOIDXX` (`FOCOIDXX`) USING BTREE;
COMMIT;