CREATE TABLE IF NOT EXISTS `MDSA2024` (
  `DOCNROXX` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero del Do',
  `SUCIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Sucursal del DO',
  `DOCSUFXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Sufijo del Do',
  `NUMSAEXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero de la SAE',
  `DEXANIOX` varchar(4) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Año CASILLA 1',
  `DEXIDDES` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero documento de identificacion CASILLA 33',
  `DEXDESID` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'IDENTIFICACION DEL DESPACHO CASILLA 44',
  `DEXDESDE` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo despacho CASILLA 44',
  `DEXPATRA` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'CODIGO DEL PAIS DEL TRAMITE CASILLA 51',
  `DEXINCID` varchar(5) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Icoterms CASILLA 56',
  `DEXANSUS` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Apellidos y nombres CASILLA 1001',
  `DEXTDSUS` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'TIPO DE DOCUMENTO DE QUIEN SUCRIBE CASILLA 1002',
  `DEXIDSUS` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'No Identificación CASILLA 1003',
  `DEXDVSUS` varchar(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'DV CASILLA 1004',
  `DEXCRSUS` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Representación CASILLA 1005',
  `DEXORSUS` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Organización CASILLA 1006',
  `DEXFHSUS` datetime NOT NULL COMMENT 'Fecha declaración exportación CASILLA 997',
  `DEXFECMA` date NOT NULL COMMENT 'DECHA DE MANIFIESTO CASILLA 134',
  `DEXIDEMT` tinytext COLLATE utf8_unicode_ci NOT NULL COMMENT 'IDENTIFICACION DEL MEDIO DE TRANSPORTE CASILLA 135',
  `DEXIDEMB` varchar(5) COLLATE utf8_unicode_ci NOT NULL COMMENT 'CODIGO DE LUGAR DE EMBARQUE CASILLA 136',
  `DEXLUEMB` tinytext COLLATE utf8_unicode_ci NOT NULL COMMENT 'LUGAR DE EMBARQUE CASILLA 136',
  `FECSAEXX` date NOT NULL COMMENT 'Fecha de la SAE',
  `MEZPXXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Mercancia se encuentra en Zona Primaria',
  `HORSAEXX` time NOT NULL COMMENT 'Hora de la SAE',
  `NUMDEXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero de formulario CASILLA 4',
  `FECDEXXX` date NOT NULL COMMENT 'Fecha del DEX',
  `NUMDEXCO` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero Dex Corregido',
  `FECDEXCO` date NOT NULL COMMENT 'Fecha Dex Correccion',
  `APLSAEGL` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica SAE Global',
  `APLSAEPR` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica SAE Provisional',
  `FECVENSA` date NOT NULL COMMENT 'Fecha de Vencimiento de la SAE',
  `NUMASUXX` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'NUMERO DE ASUNTO',
  `TIPSAEXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de SAE',
  `URLXXXXX` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Url PDF Sae',
  `CLIIDXXX` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero de identificacion CASILLA 18',
  `DVEXXXXX` varchar(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'DV CASILLA 6',
  `APL1EXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Primer apellido CASILLA 7',
  `APL2EXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Segundo apellido CASILLA 8',
  `NOM1EXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Primer nombre CASILLA 9',
  `NOM2EXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'otros nombres CASILLA 10',
  `RSOCEXXX` varchar(60) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Razon social CASILLA 11',
  `TCLIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de documento CASILLA 20',
  `CLICONXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Contacto ',
  `CLIDIRXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Direccion Exportador Local ',
  `CLITELXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Telefono Exportador Local ',
  `CLIEMAXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Email Exportador Local ',
  `CLIID2XX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Exportador ',
  `PIEIDXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Importador o Consignatario ',
  `PIENOMXX` varchar(60) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Razon social CASILLA 38',
  `DIRDEXXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Domicilio destinatario CASILLA 39',
  `PAIDESXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Pais Destinatario',
  `PIECIUXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Ciudad CASILLA 40',
  `APL1DEXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Primer apellido CASILLA 34',
  `APL2DEXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Segundo apellido CASILLA 35',
  `NOM1DEXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Primer nombre CASILLA 36',
  `NOM2DEXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'otros nombres CASILLA 37',
  `DEXPEDXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Pedido ',
  `DEXDEMXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nro Entrada Mcia ',
  `DEXDSMXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nro Salida Mcia ',
  `DEXESTXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Estado Operativo ',
  `DEXCONSU` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Contrato Suministro ',
  `TMEDESXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Regimen aduanero CASILLA 49',
  `ODIDESXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aduana despacho CASILLA 50',
  `DEXFPRXX` date NOT NULL COMMENT 'Fecha Preinspeccion ',
  `DEXNAEGL` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'N° Autorizacion de embarque global CASILLA 48',
  `DEXAGIXX` date NOT NULL COMMENT 'Fecha Inicia Global ',
  `DEXAGFXX` date NOT NULL COMMENT 'Fecha Finaliza Global ',
  `DEXFIAXX` date NOT NULL COMMENT 'Fecha Inspeccion Antinarcoticos ',
  `TCAIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo Carga ',
  `FPEIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Forma de pago CASILLA 61',
  `NATIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod naturaleza transaccional CASILLA 55',
  `SOLIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo Solicitud ',
  `ODIIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Oficina Dian ',
  `DEPIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Departamento ',
  `CIUIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Ciudad ',
  `SUCNITXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'SIA/Empresa ',
  `SUCDESXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nombre SIA/Empresa ',
  `SUCCODXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod SIA/Empresa ',
  `SUCTIPXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Tipo SIA/Empresa ',
  `USRIDXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Digitado Por ',
  `USRID2XX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Director ',
  `USRID3XX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Comparte DO Con ',
  `DAUIDXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Declarante Autorizado ',
  `DEXPAIDI` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Direccion Pais Destino ',
  `DEXPAIDE` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Pais Destino ',
  `DEXCIUDE` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Ciudad Destino ',
  `CDEIDXXX` varchar(5) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Clase DEX se debe colocar el codigo CASILLA 41',
  `TDIIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de Ddiligenciamiento CASILLA 43',
  `TCOIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de correccion CASILLA 45',
  `DEXAEMXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'N° Autorización de embarque CASILLA 82',
  `DEXFAEMX` date NOT NULL COMMENT 'Fecha autorización embarque CASILLA 83',
  `DEXNAEXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'N° Solicitud autorización de embarque CASILLA 84',
  `DEXFAEXX` date NOT NULL COMMENT 'Fecha solicitud autorización embarque CASILLA 85',
  `TDEIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Tipo Declaracion ',
  `DEXEXANX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'N° Formulario anterior CASILLA 42',
  `DEXFEXAN` date NOT NULL COMMENT 'Fecha Dec Exportacion Anterior ',
  `DEXAUANX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Declaracion Importacion Anterior ',
  `DEXFAUAN` date NOT NULL COMMENT 'Fecha Dec Importacion Anterior ',
  `MODIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Modalidad de Importacion ',
  `MOEIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Modalidad de Exportacion ',
  `DEXPBRXX` decimal(26,6) NOT NULL COMMENT 'Peso bruto Kgs ',
  `IDEDOCXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero Documento Formato 602 V7',
  `DEXPAGXX` char(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Forma de Pago ',
  `DEXNPAGX` int(11) NOT NULL COMMENT 'Cantidad de pagos anticipados CASILLA 62',
  `DEXF1PAG` date NOT NULL COMMENT 'Fecha 1er pago anticipado CASILLA 63',
  `CEMIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de embarque se debe colocar el codigo CASILLA 54',
  `TDADESXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de datos se debe colocar codigo CASILLA 53',
  `DEXNEMBX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cantidad de Embarques ',
  `TDAIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Tipo Dato ',
  `DEXEMBXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo Embaje/Embalajes ',
  `DEXCANEM` decimal(12,2) NOT NULL COMMENT 'Cantidad ',
  `DEXEMBMA` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Marcas y Numeros ',
  `CEOIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Certificado de Origen ',
  `CEOESPXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Si es Otros Especifique ',
  `DEXESPSN` varchar(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Sistemas especiales CASILLA 65',
  `DEXESPXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Sistemas Especiales ',
  `DEXREPXX` char(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Reposicion ',
  `DEXEETXX` varchar(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Exportacion en transito CASILLA 66',
  `MTRDESXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Modo de transporte CASILLA 67',
  `TCADESXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de carga CASILLA 68',
  `ADUDESXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aduana de salida CASILLA 69',
  `LANDESXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lugar de Embarque',
  `DESPAIXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Pais destino final CASILLA 70',
  `LAIDESXX` varchar(6) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod. Lugar destino final CASILLA 71',
  `ODIID2XX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Admon. de Embarque ',
  `DEXLMEXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Localizacion Mercancia ',
  `DEXNSUBX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cantidad Subpartidas Declaradas ',
  `DEXHOJAN` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Hojas Anexas ',
  `DEXTOPNT` decimal(26,6) NOT NULL COMMENT 'Total peso neto Kgs ',
  `DEXTOFOB` decimal(18,2) NOT NULL COMMENT 'Valor total FOB USD CASILLA 72',
  `DEXTOVAN` decimal(18,2) NOT NULL COMMENT 'Total valor agregado nacional USD CASILLA 78',
  `DEXTOANE` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Total Hojas Anexas ',
  `DEXFLEXX` decimal(18,2) NOT NULL COMMENT 'Valor total fletes USD CASILLA 73',
  `DEXSEGXX` decimal(18,2) NOT NULL COMMENT 'Valor total seguros USD CASILLA 74',
  `DEXOTRXX` decimal(18,2) NOT NULL COMMENT 'Valor total otros gastos USD CASILLA 75',
  `DEXTOTAL` decimal(18,2) NOT NULL COMMENT 'Valor total exportaciones USD CASILLA 76',
  `DEXREINT` decimal(18,2) NOT NULL COMMENT 'Valor a reintegrar USD CASILLA 77',
  `DEXPROEM` char(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Procede el Embarque ',
  `DEXFECEM` date NOT NULL COMMENT 'Fecha Embarque ',
  `DEXAUTOA` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Auto ',
  `DEXNMANX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'No. Manifiesto Carga ',
  `ODIID3XX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Admon Cert Embarque ',
  `DEXBULXX` decimal(26,6) NOT NULL COMMENT 'Bultos Cert. Emb ',
  `DEXPESXX` decimal(26,6) NOT NULL COMMENT 'Peso Kgs Cert Emb ',
  `DEXIDTRA` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Identificacion Medio Transporte ',
  `DEXDEXXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Declaracion Exportacion ',
  `DEXFECXX` date NOT NULL COMMENT 'Fecha Declaracion Exp ',
  `DEXDOCXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Doc Transporte ',
  `DEXFDOCX` date NOT NULL COMMENT 'Fecha Doc Transporte ',
  `DEXMASTX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Master ',
  `DEXFMAST` date NOT NULL COMMENT 'Fecha Master ',
  `LINIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Lugar Salida ',
  `DEPID2XX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Region de procedencia CASILLA 52',
  `RGIIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Regional Mincomercio ',
  `MONIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Moneda de transaccion CASILLA 58',
  `DEXMONNE` decimal(18,2) NOT NULL COMMENT 'Valor factura en moneda de transaccion CASILLA 59',
  `MTRIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Modo Transporte ',
  `DEXBANXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Bandera ',
  `DEXOBSXX` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Observaciones ',
  `DEXSANVL` decimal(10,2) NOT NULL COMMENT 'Valor Total Solicitud Anticipo ',
  `DEXSANFE` date NOT NULL COMMENT 'Fecha Recepcion Anticipo ',
  `DEXSANSO` date NOT NULL COMMENT 'Fecha Solicitud Anticipo ',
  `DEXSANOB` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Observaciones Solicitud Anticipo ',
  `DEXTASAX` decimal(10,4) NOT NULL COMMENT 'Tasa de cambio CASILLA 60',
  `DEXTARXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nro Tarea ',
  `PRYIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod. Proyecto Alpopular ',
  `DIVIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod. Division Alpopular ',
  `TERIDXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Codigo Tercero Alp ',
  `TRLIDXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ID Transportador Local ',
  `DVTRXXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'DV Transportador',
  `TRLAPE1X` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Primer Apellido Transportador',
  `TRLAPE2X` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Segundo Apellido Transportador',
  `TRLNOM1X` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Primer Nombre Transportador',
  `TRLNOM2X` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Otros Nombres Transportador',
  `TRLDESXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Razon Social Transportador',
  `BODDESXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lugar Transportador',
  `DEXDIPXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Diplomatico ',
  `TIPDECSA` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de documento CASILLA 24',
  `SUCNITDE` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero documento de identificacion CASILLA 25',
  `DVDCXXXX` varchar(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'DV CASILLA 26',
  `APL1DCXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Primer apellido CASILLA 27',
  `APL2DCXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Segundo apellido CASILLA 28',
  `NOM1DCXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Primer nombre CASILLA 29',
  `NOM2DCXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'otros nombres CASILLA 30',
  `SUCDESDE` varchar(60) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Razon social CASILLA 31',
  `TDIID2XX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de documento CASILLA 32',
  `CETIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Incoterms ',
  `DEXLUGEX` varchar(60) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lugar de entrega CASILLA 57',
  `DEXMANOX` varchar(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Mercancia a la mano con el viajero CASILLA 64',
  `DEXPAIDF` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Pais destino final ',
  `LAIIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Lugar Destino Final ',
  `LANIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lugar Embarque ',
  `DHZIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Deposito habilitado Zona Franca ',
  `DEXCIFCO` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod destino final Colombia ',
  `DEHDESXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Deposito Habilitado',
  `TDIDESXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo Documento transportador',
  `DEHIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Deposito habilitado ',
  `DEXNAPZS` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nro Aprobacion Solicitud inspeccion en Zona Secundaria ',
  `DEXUBMER` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Direccion Ubicacion Mcia ',
  `DEXINSFI` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Solicita inspeccion fisica ',
  `DEXTOTSE` int(11) NOT NULL COMMENT 'Total series CASILLA 79',
  `DEXMERLE` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Mcia se encuentra en lugar embarque ',
  `DEXNROVI` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nro Viaje ',
  `TDOCXXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo documento Documentos Soporte y Vistos Buenos',
  `NDOCXXXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'No. del documento Documentos Soporte y Vistos Buenos',
  `NITEMXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NIT emisor Documentos Soporte y Vistos Buenos',
  `FEXPXXXX` date NOT NULL COMMENT 'Fecha expedición Documentos Soporte y Vistos Buenos',
  `FVENXXXX` date NOT NULL COMMENT 'Fecha vencimiento Documentos Soporte y Vistos Buenos',
  `CMONXXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Moneda Documentos Soporte y Vistos Buenos',
  `MONDOCXX` int(50) NOT NULL COMMENT 'Monto del documento Documentos Soporte y Vistos Buenos',
  `DEXFFCTM` date NOT NULL COMMENT 'Fecha Finaliza Control Temporal ',
  `DEXOFCTM` decimal(1,0) NOT NULL COMMENT 'Finaliza Control Temporal ',
  `DEXMOCTM` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Motivo Finaliza Control Temporal ',
  `DEXREFXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'N° Referencia CASILLA 46',
  `DEXNUENV` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero de Envio ',
  `SAENOFOR` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero de Formulario para la SAE ',
  `DEXCSCFX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero de la Exportacion (Consecutivo Asignado por Finart) ',
  `DEXURLXX` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'URL del dex enviado por tramitex',
  `SUBPREXX` int(30) NOT NULL COMMENT 'Subpartida Precedente',
  `VRIEXXXX` int(30) NOT NULL COMMENT 'Valor insumo externo (VIE)',
  `VALVANXX` int(30) NOT NULL COMMENT 'Valor agregado nacional (VAN)',
  `CPECIPXX` int(30) NOT NULL COMMENT 'Cantidad Producto a exportar por CIP',
  `NPRODXXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'No. Producto',
  `NCIPXXXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'No. Cuadro insumo producto (CIP)',
  `NPROGXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'N° programa especial de muestras o contrato de suministro de energia CASILLA 47',
  `SERIEXXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'No Serie',
  `SERPREXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'No. Serie precedente',
  `CMODPREX` int(30) NOT NULL COMMENT 'Cód. Modalidad precedente',
  `CREGPREX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cód. Rég. Precedente',
  `ANOACEPX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Año aceptación',
  `NDECPREX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'No. Declaración precedente',
  `CADEPREX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aduana precedente',
  `PRFARANX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Preferencia arancelaria',
  `PORGXXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'País de origen',
  `PLAZOXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Plazo',
  `CUNMPLAX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Unidad medida de plazo',
  `VALFOBXX` int(30) NOT NULL COMMENT 'Valor FOB USD',
  `PESNETXX` int(20) NOT NULL COMMENT 'Peso neto kgs.',
  `PESBULXX` decimal(18,2) NOT NULL COMMENT 'Total peso bruto kgs CASILLA 81',
  `NUMBULXX` int(11) NOT NULL COMMENT 'Total número de bultos CASILLA 80',
  `CAUNCOMX` int(20) NOT NULL COMMENT 'Cant. Unidades comerciales',
  `UNICOMXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Unidad comercial',
  `CANUNFIX` int(20) NOT NULL COMMENT 'Cant. Unidades físicas',
  `CODUNFIX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Unidad física',
  `CSUPLXXX` int(60) NOT NULL COMMENT 'Cód. Suplement.',
  `CCOMXXXX` int(60) NOT NULL COMMENT 'Cód. Complement',
  `SUBARXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Subpartida',
  `CUNCOMXX` int(30) NOT NULL COMMENT 'Cantidad unidad comercial Documentos Soporte y Vistos Buenos',
  `GRUPOXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Grupo',
  `FACSEMAN` int(11) NOT NULL COMMENT 'Numeo de Semana',
  `AEROPUXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aeropuerto SAE',
  `AEROLIXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aerolinea SAE',
  `DESTINOX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Destino SAE',
  `LUGARXXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lugar SAE',
  `NUMPROXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lugar SAE',
  `FECPROXX` date NOT NULL COMMENT 'Fecha de la Prorroga',
  `BANSAEXX` enum('PENDIENTE','CARGADO','HISTORIAL','ERROR') COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Bandera para identificar las SAEs Pendientes o Cargadas a GENIO',
  `BANPLAXX` enum('CARGADO','ERROR') COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Bandera para identificar las Planillas de Traslado cargadas a GENIO',
  `BANDEXXX` enum('PENDIENTE','CARGADO','HISTORIAL','ERROR') COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Bandera para identificar los DEXs Pendientes o Cargados a GENIO',
  `ERRSAEXX` text COLLATE utf8_unicode_ci COMMENT 'Errores en la SAE al cargue a GENIO',
  `ERRPLAXX` text COLLATE utf8_unicode_ci COMMENT 'Errores en la Planilla de Traslado al cargue a GENIO',
  `ERRDEXXX` text COLLATE utf8_unicode_ci COMMENT 'Errores en la DEX al cargue a GENIO',
  `FILESAPL` mediumtext COLLATE utf8_unicode_ci NOT NULL COMMENT 'Urls Files de SAE y Planilla Cargados a Genio',
  `ESTELIMX` enum('PENDIENTE','ELIMINADO','ERROR','PARCIAL','NA') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NA' COMMENT 'Estado Archivos a Eliminar de GENIO',
  `ERRELIMX` text COLLATE utf8_unicode_ci COMMENT 'Errores al eliminar archivos de SAE o Planilla de GENIO',
  `PACKSAPL` tinytext COLLATE utf8_unicode_ci NOT NULL COMMENT 'Id del paquete documental de SAE y Planilla cargados a Genio',
  `ERRPSAPL` text COLLATE utf8_unicode_ci COMMENT 'Errores al inactivar los paquetes de SAE y Planilla cargados a Genio',
  `ESTATEMP` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ESTADO TEMPORAL',
  `APLIPROX` enum('SI','NO') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'SI' COMMENT 'Aplica Prorroga',
  `NUMRADXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'N° radicación CASILLA 90',
  `FECRADXX` date NOT NULL COMMENT 'Fecha de radicado',
  `FECAUPRX` date NOT NULL COMMENT 'Fecha de autoprorroga',
  `REGUSRXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `REGFECXX` date NOT NULL,
  `REGHORXX` time NOT NULL,
  `REGUSRMX` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `REGFECMX` date NOT NULL,
  `REGMODXX` date NOT NULL,
  `REGHORMX` time NOT NULL,
  `REGESTXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`DOCNROXX`,`NUMSAEXX`) USING BTREE,
  KEY `DOCNROXX` (`DOCNROXX`),
  FULLTEXT KEY `NUMASUXX` (`NUMASUXX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Datos de SAE y DEX';
