CREATE TABLE `CIPO0001` (
  `CAPSUBXX` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DEL CAPITULO ',
  `PARSUBXX` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DE LA PARTIDA',
  `ARMSUBXX` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DEL SISTEMA ARMONIZADO',
  `ANDSUBXX` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DE LA ANDINA',
  `SUBSUBXX` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DE 2 DIGITOS DE LA SUBPARTIDA',
  `SUBIDXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID de la subpartida',
  `SUBDESXX` tinytext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'DESCRIPCION DE LA SUBPARTIDA',
  `UNIIDXXX` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID DE LA UNIDAD ',
  `SUBAPVIX` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'APLICA VIGENCIA',
  `SUBVIINX` date NOT NULL COMMENT 'fecha inicial de la vigencia',
  `SUBAPATX` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'aplica arancel temporal',
  `SUBARTMX` decimal(4,0) NOT NULL COMMENT 'porcentaje de arancel TEMPORAL',
  `SUBARINX` date NOT NULL COMMENT 'fecha inicial de la vigencia ARANCEL TEMPORAL',
  `SUBARFNX` date NOT NULL COMMENT 'fecha FINAL de la vigencia ARANCEL TEMPORAL',
  `SUBAPITX` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'aplica IVA temporal',
  `SUBIVTMX` int NOT NULL COMMENT 'porcentaje de IVA TEMPORAL',
  `SUBIVINX` date NOT NULL COMMENT 'fecha inicial de la vigencia IVA TEMPORAL',
  `SUBIVFNX` date NOT NULL COMMENT 'fecha FIN de la vigencia IVA TEMPORAL',
  `SUBAPVCX` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI APLICA VUCE',
  `TRIIDXXX` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'COD TIPO REGISTRO',
  `SUBCODSU` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CODIGO SUPLEMENTARIO',
  `SUBCODCO` varchar(4) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CODIGO COMPLEMENTARIO',
  `SUBCAUFI` enum('','CORRELACION DIRECTA','DESDOBLAMIENTO','ELIMINACION') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'CAUSAL DE FINALIZACION',
  `SUBAPLFP` enum('','SI','NO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI APLICA FRANJA DE PRECIOS',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='SUBPARTIDAS' ROW_FORMAT=COMPACT;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `CIPO0001`
--
ALTER TABLE `CIPO0001`
  ADD PRIMARY KEY (`CAPSUBXX`,`PARSUBXX`,`ARMSUBXX`,`ANDSUBXX`,`SUBSUBXX`,`SUBIDXXX`),
  ADD KEY `CAPSUBXX` (`CAPSUBXX`) USING BTREE,
  ADD KEY `PARSUBXX` (`PARSUBXX`) USING BTREE,
  ADD KEY `ARMSUBXX` (`ARMSUBXX`) USING BTREE,
  ADD KEY `ANDSUBXX` (`ANDSUBXX`) USING BTREE,
  ADD KEY `UNIIDXXX` (`UNIIDXXX`) USING BTREE,
  ADD KEY `TRIIDXXX` (`TRIIDXXX`),
  ADD KEY `SUBIDXXX` (`SUBIDXXX`);
COMMIT;
