CREATE TABLE `GRM00350` (
  `CLIIDXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Id del cliente',
  `OPENIDXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'campo id open',
  `CLIIDDEX` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CLINOMXX` varchar(250) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Razon social',
  `CLINOMCX` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CLINICKX` varchar(150) COLLATE utf8_unicode_ci NOT NULL,
  `TPEIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Tipo de Persona',
  `TDIIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Tipo de Identificacion',
  `CLITCLXX` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `PAIIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Pais',
  `DEPIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Departamento',
  `CIUIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Ciudad',
  `CLIDIRXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Direccion',
  `CLITELXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Telefono',
  `CLIFAXXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Fax',
  `CLICELXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Celular',
  `CLIEMIXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Mail',
  `CLIEMSOD` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lista de cuentas de correo electronicos para SODIMAC',
  `CLIWEBXX` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Web',
  `ALIIDXXX_OLD` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `PAIIDCXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `DEPIDCXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cod Departamento Correspondencia',
  `CIUIDCXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CLIDIRCX` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `AECIDXXX_OLD` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `AECID2XX_OLD` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `AECID3XX_OLD` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `CLICCFEC` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Camara y Comercio',
  `CLIRUFEC` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de Rut',
  `CLIICFEC` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha  de Circular',
  `CLIIVAXX_OLD` char(1) COLLATE utf8_unicode_ci NOT NULL,
  `CLIGCRES_OLD` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `CLIGCFEC_OLD` date NOT NULL DEFAULT '0000-00-00',
  `CLIARRES_OLD` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `CLIARFEC_OLD` date NOT NULL DEFAULT '0000-00-00',
  `CLIERRES_OLD` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `CLIERFEC_OLD` date NOT NULL DEFAULT '0000-00-00',
  `CLIOBSXX` text COLLATE utf8_unicode_ci NOT NULL,
  `CLICSCXX_OLD` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `CLICSCNI_OLD` int(10) NOT NULL DEFAULT '0',
  `CLISIAXX_OLD` char(1) COLLATE utf8_unicode_ci NOT NULL,
  `CLIMAPXX_OLD` char(1) COLLATE utf8_unicode_ci NOT NULL,
  `CLIRM1XX_OLD` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `CLIRM2XX_OLD` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `CLIGRCON` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Gran contribuyente',
  `CLIAURET` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Autoretenedor',
  `CLIRECOM` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Regimen comun',
  `CLIRESIM` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Regimen simplificado',
  `CLIACECO` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Actividad economica',
  `CLIRENOM` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nombre Representante legal',
  `CLIRECAR` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cargo Representante legal',
  `CLIRETEL` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Telefono Representante legal',
  `CLIREEMI` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Mail Representante legal',
  `CLIPDEXP` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Pais de origen Importacion',
  `CLITPMER` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de Mercancia',
  `CLIADUIM` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Cod. Aduana de Importacion',
  `CLIADUEM` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Cod. Aduana de Embarque',
  `CLICUPEX` decimal(19,2) DEFAULT NULL COMMENT 'Cupo de comercio Ext.',
  `CLICERSE` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Certificacion de seguridad',
  `CLIDESSE` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Otra certificacion',
  `CLIVISSE` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Visita de seguridad',
  `CLIFECVI` date DEFAULT NULL COMMENT 'Fecha visita seg.',
  `CLICALVI` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Calificacion visita seg.',
  `CLIMONXX` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Monitoreo',
  `CLIMATRI` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Matriz de riesgos',
  `CLIMATRN` enum('','ALTA','MEDIA','BAJA') COLLATE utf8_unicode_ci DEFAULT '' COMMENT 'Medida de matriz de riesgo',
  `CMAMATRI` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Matriz de riesgos Map',
  `CMAMATRN` enum('','ALTA','MEDIA','BAJA') COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Medida de matriz de riesgo Map',
  `CLIMAPIM` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Importaciones maritimas Map',
  `PROINGME` int(9) DEFAULT NULL COMMENT 'Promedio de ingresos mensuales',
  `CLIPORGI` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Pais de origen Importacion',
  `CLIAEROA` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Aerodino',
  `APLIMPSK` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Impresion Sticker Logistica Repremundo',
  `APLIDCLI` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Identificacion Cliente Pedido',
  `CLIEMPSEL` tinytext COLLATE utf8_unicode_ci COMMENT 'empresas seleccionadas para visita',
  `PESCATXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Descripcion de la categoria',
  `FECPROIG` date NOT NULL COMMENT 'Fecha registro promedio de ingresos por interfaz',
  `REGUSRXX` varchar(12) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Usuario creacion',
  `REGFECXX` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha de creacion',
  `REGMODXX` date NOT NULL DEFAULT '0000-00-00',
  `REGHORXX` varchar(5) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `REGESTXX` varchar(15) COLLATE utf8_unicode_ci NOT NULL,
  `ESTRISXX` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Estado RIS',
  `CLIESTCO` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Estado de Conocimiento del Cliente.',
  `CLIDATCO` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `CLIICAXX_OLD` tinyint(1) NOT NULL DEFAULT '0',
  `CLIGRUXX_OLD` int(12) NOT NULL DEFAULT '0',
  `CLILEGAL_OLD` tinyint(1) NOT NULL DEFAULT '0',
  `CLIEIRXX_OLD` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `CLIEIFXX_OLD` date NOT NULL DEFAULT '0000-00-00',
  `CLINUAPX_OLD` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `CLINATXX_OLD` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `CLILUXXX_OLD` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `CLISIAEX_OLD` char(1) COLLATE utf8_unicode_ci NOT NULL,
  `CLIMAPEX_OLD` char(1) COLLATE utf8_unicode_ci NOT NULL,
  `CLIRM1EX_OLD` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `CLIRM2EX_OLD` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `CLITMCIA_OLD` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `CLIUAPXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `CLIUAPCO` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `CLIALTEX` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `CLIALTEC` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `CLIOPEXX_OLD` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `CLIPLAXX_OLD` varchar(3) COLLATE utf8_unicode_ci NOT NULL,
  `CLIANTXX_OLD` varchar(12) COLLATE utf8_unicode_ci NOT NULL,
  `CLIINTXX_OLD` varchar(12) COLLATE utf8_unicode_ci NOT NULL,
  `GRUIDXXX` varchar(5) COLLATE utf8_unicode_ci NOT NULL,
  `CLIIFAXX_OLD` varchar(12) COLLATE utf8_unicode_ci NOT NULL,
  `CLIEMAXX` longtext COLLATE utf8_unicode_ci NOT NULL,
  `TARFINIX_OLD` date NOT NULL,
  `TARFFINX_OLD` date NOT NULL,
  `CLINCOTX_OLD` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `CLIDFAXX_OLD` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `CLIACIXX_OLD` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `CLIAGMCX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Es Mapcargo',
  `CLIDR1XX` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `CLIDR2XX` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `CLIDRIND` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Comprueba Si el Cliente tambien es un Cliente de Repremundo Industrial de Servicios',
  `CLIDZFXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `CLISIEXP` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `CLISIDTA` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `CLIINAXX` date NOT NULL COMMENT 'Fecha de Inactivacion',
  `DATFECXX` date NOT NULL COMMENT 'Fecha Datacredito',
  `DATHORXX` time NOT NULL COMMENT 'Hora Datacredito',
  `CLIADTXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Autorizacion DataCredito',
  `CLIPROGE` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Plantillas Genericas que Aplican para el Cliente',
  `CLIANSXX` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Ans que Aplican para el Cliente',
  `CLILOGRE` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Indica si el cliente aplica para Logistica Repremundo',
  `AGENADUA` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Agencia de Aduana Datos Generales Logistica',
  `AEROLINE` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Aerolina Datos Generales Logistica',
  `ORDENCOG` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Orden de Compra Datos Generales Logistica',
  `FACTURAG` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Factura Datos Generales Logistica',
  `ORDENCOM` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica orden de compra Detalle de mercancia Logistica Repremundo',
  `FACTURAX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica factura A Nivel de Detalle Logistica Repremundo',
  `POITEMNO` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'PO Item No Detalle de Item Logistica',
  `DOCUMENT` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Documento Detalle de Item  Logistica',
  `PLANTAXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Planta Logistica',
  `REGESLOG` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Estado de Cliente para Logistica Repremundo',
  `MAPCLIXX` varchar(5) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Cliente de Mapcargo',
  `MAPTIPXX` varchar(50) COLLATE utf8_unicode_ci DEFAULT 'CLIENTE' COMMENT 'Tipo de cliente mapcargo',
  `MAPTOPHA` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'tipo operacion habilitada',
  `MAPCONNA` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombres del contacto map',
  `MAPCONAP` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Apsllidos del contacto map',
  `MAPCONEM` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Email del contacto map',
  `MAPLIBDO` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'acutoriza liberacion de documentos',
  `MAPFEVI1` date DEFAULT NULL COMMENT 'fecha de visita 1',
  `MAPTIVI1` time DEFAULT NULL COMMENT 'hora de visita 1',
  `MAPDIVI1` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'direccion de visita 1',
  `MAPFEVI2` date DEFAULT NULL COMMENT 'fecha de visita 2',
  `MAPTIVI2` time DEFAULT NULL COMMENT 'hora de visita 2',
  `MAPDIVI2` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'direccion de visita 2',
  `MAPFEVI3` date DEFAULT NULL COMMENT 'fecha de visita 3',
  `MAPTIVI3` time DEFAULT NULL COMMENT 'hora de visita 3',
  `MAPDIVI3` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'direccion de visita 3',
  `MAPMAGID` varchar(50) COLLATE utf8_unicode_ci DEFAULT '' COMMENT 'GUID de Magaya',
  `PROGUIDX` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Guid proveedor',
  `AGEGUIDX` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Guid agente',
  `TRAGUIDX` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Guid transportador',
  `CLIHUBSP` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Id empresa hubspot',
  `CONHUBSP` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Id contacto hubspot',
  `CHECKHUB` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'check migrar a hubspot',
  `MAPCONCR` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Cliente con credito',
  `MAPAPRCR` date DEFAULT NULL COMMENT 'Fecha aprobación del credito',
  `MAPVENCR` date DEFAULT NULL COMMENT 'Fecha vencimiento credito',
  `MAPCUPCR` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Cupo credito',
  `MAPTERPA` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Termino de pago',
  `MAPACTPR` date DEFAULT NULL COMMENT 'Actualización Doc a Proveedor',
  `EMAIFACM` varchar(150) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Correo facturacion electronica mapcargo',
  `FECSOLDO` date DEFAULT NULL COMMENT 'fecha solicitud documental',
  `FECSOLAC` date DEFAULT NULL COMMENT 'Envio Sarlaft',
  `FECDOCOR` date DEFAULT NULL COMMENT 'Fecha de documentos originales',
  `CLIORIRE` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Tipo de solicitud',
  `MAPESTXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'POTENCIAL' COMMENT 'Estado Mapcargo',
  `CLIIDINT` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MAPIMPXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Importacion Mapcargo',
  `MAPEXPXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Exportacion Mapcargo',
  `CHECKNOT` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Notificar a conocimiento a clientes',
  `CLIFECZA` date DEFAULT NULL COMMENT 'Fecha zarpe o llegada',
  `MODTRANX` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Modo transporte',
  `CLIREFXX` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Quien refiere el cliente',
  `CLIMANOP` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Quien maneja la operacion',
  `CLIVALME` varchar(25) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Valor mercancia',
  `PROVOPDE` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Tipo Proveedor Operativo',
  `CLICAREC` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Caracteristica reconocimientos',
  `MAPCOTXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cotizacion Map',
  `CLIOCPRE` varchar(5) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Prefijo para Consecutivo de Orden de Compra del Cliente',
  `CLIOCSEP` varchar(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Separador para Consecutivo de Orden de Compra del Cliente',
  `CLIOCLON` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Logitud del Consecutivo de Orden de Compra del Cliente',
  `CLICSCAU` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Consecutivo Automatico del Cliente',
  `CLICSCLO` int(11) NOT NULL COMMENT 'Longitud del consecutivo del Cliente',
  `CLIOCTLO` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de Caracteres para Ordenes de Compra',
  `CLIPEAUT` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Consecutivo automatco de Pedido',
  `CLIPELON` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Longitud del Consecutivo de Pedido',
  `CLIPECSC` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Consecutivo Pedido del Cliente.',
  `CLISEPRA` int(1) NOT NULL COMMENT 'Separador Estructura del Pedido para el Cliente',
  `CLINICNA` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `ORDENICK` int(11) NOT NULL COMMENT 'Orden Nick Name del Proveedor',
  `CLIENPED` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Pedido',
  `ORDEPEDI` int(11) NOT NULL COMMENT 'Orden del Pedido',
  `CLIENDIV` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Division Sigla',
  `ORDEDIVI` int(11) NOT NULL COMMENT 'Orden de la Division',
  `CLISEPFA` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Separador de Datos Pedido que sale en la impresion de la factura. ',
  `CLIDOCFA` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Aplica Documento de Transporte en el campo de pedido de la factura. ',
  `CLIORDFA` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Aplica Ordenes de Compra en el campo de pedido de la factura.',
  `CLIPEDFA` varchar(2) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Aplica Pedido en el campo de pedido de la factura.',
  `ORDEDOCT` int(11) NOT NULL COMMENT 'Orden del Documento de Transporte',
  `ORDECOMP` int(11) NOT NULL COMMENT 'Orden de la Orden de Compra',
  `ORDFAPED` int(11) NOT NULL COMMENT 'Orden del Pedido',
  `CLICULXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cliente Cultivo',
  `CLICONOP` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Control de Operacion DO o OC/Pedido',
  `CLIAPLSU` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica subpartida definida por el cliente',
  `CLICODIN` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Codigo Interno Cliente',
  `CLIDELIV` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Delivery Number',
  `CLIORDER` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Order Number',
  `CLIORIGE` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Planta Origen',
  `CLIDESTI` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Planta Destino',
  `CLILINEA` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Lineas de Producto',
  `CLIDESEF` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Descripcion Segun Factura para la Declaracion',
  `CLIENTUR` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'El cliente puede hacer operaciones de entrega urgente',
  `CLIENMIG` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'El Cliente Migra Declaracion por Factura',
  `CLIPRETE` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Prefijo Temportal',
  `CLIDRCTG` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Cliente Repre CTG',
  `NOMZIPXX` tinytext COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nombre archivo ZIP',
  `NOMDECXX` tinytext COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nombre Declaracion',
  `BANTIPDE` enum('','COMPLETA','DIVIDIDA') COLLATE utf8_unicode_ci NOT NULL COMMENT 'Bandera declaracion',
  `BANDAVVA` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'BANDERA QUE INDICA SI SE DEBE MOSTRAR LOS VALORES DE LA DECLARACION CON VALORES',
  `APWMSLOG` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Indica si el cliente utiliza el WMS de logistica Repremundo',
  `ASUNAVIS` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Indica que el Asunto debe Ser Control de Inventario y se debe agrupar el correo en el aviso,informe de entrada y salida',
  `OBSREFXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Observacion Detalle de Mercancia Logistica Repremundo',
  `APLESPEX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Presentacion Detalle de Mercancia Logistica Repremundo',
  `APDTRDAT` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Peso y Bultos en Datos de Llegada, Trafico Internacional',
  `SOLURGDF` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Indica si las solicitudes de Grupos de Apoyo tiene prioridad urgente por default',
  `SOLURGAU` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Marca Default Urgente Auditoria',
  `APLVALNA` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica Validaciones de Nacionalizacion de Mercancia en Inventario',
  `TIPOAUDI` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de Auditoria del Cliente.',
  `APLANTIC` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aplica solicitud de anticipo',
  `SISSEGUR` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Sistema de seguridad',
  `FORDECXX` enum('','PDF','JPG') COLLATE utf8_unicode_ci NOT NULL COMMENT 'Indica el formato de las declaraciones',
  `FUNCONXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'FUNCION DE CONDICIONES ESPECIALES',
  `DATEXTCL` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Datos de Informacion extra del cliente',
  `DOCPENCL` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Documento Pendiente del cliente',
  `NUMPOLIZ` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero Poliza',
  `ESALICOM` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Marca que Indica si el Cliente Es un Aliado Comercial',
  `CLIIDALI` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nit Aliado Comercial',
  `APTIOBDF` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Indica si el cliente desea tipificar todas las observaciones a nivel general',
  `TIPOBSDF` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de Observacion Default',
  `OEAXXXXX` enum('SI','NO') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Campo OEA',
  `FECRESOL` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Resolucion',
  `NUMRESOL` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero Resolución',
  `CANTPGEN` int(10) NOT NULL COMMENT 'Cantidad Puerto Vencimiento',
  `UNIDPGEN` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Unidad de Medida Puerto',
  `CANTNGEN` int(10) NOT NULL COMMENT 'Cantidad Naviera Vencimiento',
  `UNIDNGEN` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Unidad de Medida Puerto',
  `CANOPEAL` int(11) NOT NULL COMMENT 'Indica la cantidad de operaciones con prioridad alta',
  `EMAIFACE` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Correo Electronico Factura Electronica',
  `FACEESPC` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de Operacion Especifica para Facturacion Electronica',
  `EMAIFAES` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Correo Electronico Factura Electronica Especifica',
  `EMAIFAEL` tinytext COLLATE utf8_unicode_ci NOT NULL COMMENT 'Correos de facturacion electronica Logistica',
  `SERVESCO` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Servicio de escolta transporte',
  `CLISIACO` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Indica si el cliente es de SIaco',
  `CLIDIVEN` date NOT NULL COMMENT 'Fecha Vigencia Poliza Logistica',
  `CLIDIVEF` int(2) NOT NULL COMMENT 'Numero de dias vencimiento factura Logistica',
  `BANPSEPA` enum('NO','SI') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Bandera que indica si el cliente permite pagos PSE',
  `USRAPTOX` enum('','SI','NO','EN PROCESO') COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'Usuario Apto',
  `USRAPTOC` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Código Usuario Apto',
  `EXPOEAXX` enum('SI','NO') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Exportador OEA',
  `EXPFECRE` date NOT NULL DEFAULT '0000-00-00' COMMENT 'Fecha Resolucion Expo',
  `EXPNUMRE` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Numero Resolución Expo',
  `APLIAUEU` enum('SI','NO') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Bandera que indica si aplica auditoria cuando maneje operaciones de entrega urgente',
  `APLIBLEX` enum('SI','NO') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Control desbloqueo EDI',
  `APLIBLLX` enum('SI','NO') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Control desbloqueo Levante',
  `APLIMPXX` enum('SI','NO') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'indica si el cliente aplica impresion',
  `APLCONTE` enum('NO','SI') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Bandera que indica si aplica consulta pagos a terceros',
  `ESTRCORX` tinytext COLLATE utf8_unicode_ci NOT NULL COMMENT 'Asunto del Correo',
  `CORSEGXX` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Correos de seguimiento del cliente',
  `CLIICEVA` enum('','SI') COLLATE utf8_unicode_ci NOT NULL COMMENT 'Aliado CEVA',
  `AUVACEVA` enum('','SI') COLLATE utf8_unicode_ci NOT NULL COMMENT 'Auditoria X Valor Aliado CEVA',
  `AUPOCEVA` enum('','SI') COLLATE utf8_unicode_ci NOT NULL COMMENT 'Auditoria X Porcentaje Aliado CEVA',
  `VALOCEVA` smallint(6) NOT NULL COMMENT 'Valor Auditoria CEVA',
  `DESSUBXX` enum('SI','NO') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'NO' COMMENT 'Despacho con Subpartidas',
  `CLIBANFD` enum('SI','NO') COLLATE utf8_unicode_ci NOT NULL,
  `REGFECMR` date NOT NULL COMMENT 'Fecha de Modificacion del Registro Para RIO',
  `REGHORMR` time NOT NULL COMMENT 'Hora de Modificacion del Registro Para RIO',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFICADO'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='CLIENTES';

--
-- Disparadores `GRM00350`
--
DELIMITER $$
CREATE TRIGGER `insGRM350` BEFORE INSERT ON `GRM00350` FOR EACH ROW BEGIN
DECLARE ced INT;
DECLARE nci VARCHAR(50);
IF(NEW.CLIAGMCX = 'SI') THEN
INSERT INTO MAPCARGO.GRM00350 (MAPMAGID,MAPTIPXX,CLIIDXXX,CLINOMXX,CLIDIRXX,CLIEMIXX,CLIRENOM,CLINOMCX,CLITELXX,CLIIDDEX,CIUIDXXX,DEPIDXXX,PAIIDXXX,CLIRECOM,
	CLIRESIM,EMAIFACM,REGUSRXX,REGFECXX,REGMODXX,REGHORXX,MAPESTXX,TDIIDXXX,TPEIDXXX)
	VALUES (NEW.MAPMAGID,NEW.MAPTIPXX,NEW.CLIIDXXX,NEW.CLINOMXX,NEW.CLIDIRXX,NEW.CLIEMIXX,NEW.CLIRENOM,NEW.CLINOMCX,NEW.CLITELXX,NEW.CLIIDDEX,NEW.CIUIDXXX,NEW.DEPIDXXX,
	NEW.PAIIDXXX,NEW.CLIRECOM,NEW.CLIRESIM,NEW.EMAIFACM,NEW.REGUSRXX,NEW.REGFECXX,NEW.REGMODXX,NEW.REGHORXX,NEW.MAPESTXX,NEW.TDIIDXXX,NEW.TPEIDXXX);	
END IF;
SET NEW.`REGFECMR`= NOW();
SET NEW.`REGHORMR`= NOW();

END
$$
DELIMITER ;
DELIMITER $$
CREATE TRIGGER `updGRM350` BEFORE UPDATE ON `GRM00350` FOR EACH ROW BEGIN
DECLARE ced INT;
DECLARE nci VARCHAR(50);
DECLARE ID VARCHAR(50);

SET NEW.`REGFECMR`= NOW();
SET NEW.`REGHORMR`= NOW();

IF(NEW.CLIAGMCX = 'SI') THEN
	SET ID = (SELECT cliidxxx FROM MAPCARGO.GRM00350 WHERE cliidxxx=NEW.CLIIDXXX);
	IF(ID IS NULL) THEN
		INSERT INTO MAPCARGO.GRM00350 (MAPMAGID,MAPTIPXX,CLIIDXXX,CLINOMXX,CLIDIRXX,CLIEMIXX,CLIRENOM,CLINOMCX,CLITELXX,CLIIDDEX,CIUIDXXX,DEPIDXXX,PAIIDXXX,CLIRECOM,
		CLIRESIM,EMAIFACM,REGUSRXX,REGFECXX,REGMODXX,REGHORXX,MAPESTXX,TDIIDXXX,TPEIDXXX)
		VALUES (NEW.MAPMAGID,NEW.MAPTIPXX,NEW.CLIIDXXX,NEW.CLINOMXX,NEW.CLIDIRXX,NEW.CLIEMIXX,NEW.CLIRENOM,NEW.CLINOMCX,NEW.CLITELXX,NEW.CLIIDDEX,NEW.CIUIDXXX,NEW.DEPIDXXX,
		NEW.PAIIDXXX,NEW.CLIRECOM,NEW.CLIRESIM,NEW.EMAIFACM,NEW.REGUSRXX,NEW.REGFECXX,NEW.REGMODXX,NEW.REGHORXX,NEW.MAPESTXX,NEW.TDIIDXXX,NEW.TPEIDXXX);	
	ELSEIF(ID IS NOT NULL) THEN
		UPDATE MAPCARGO.GRM00350 SET MAPMAGID=NEW.MAPMAGID,MAPTIPXX=NEW.MAPTIPXX,CLINOMXX=NEW.CLINOMXX,CLIDIRXX=NEW.CLIDIRXX,CLIEMIXX=NEW.CLIEMIXX,
		CLIRENOM=NEW.CLIRENOM,CLINOMCX=NEW.CLINOMCX,CLITELXX=NEW.CLITELXX,CLIIDDEX=NEW.CLIIDDEX,CIUIDXXX=NEW.CIUIDXXX,DEPIDXXX=NEW.DEPIDXXX,PAIIDXXX=NEW.PAIIDXXX,
		CLIRECOM=NEW.CLIRECOM,CLIRESIM=NEW.CLIRESIM,EMAIFACM=NEW.EMAIFACM,REGUSRXX=NEW.REGUSRXX,REGFECXX=NEW.REGFECXX,REGMODXX=NEW.REGMODXX,
		REGHORXX=NEW.REGHORXX,MAPESTXX=NEW.MAPESTXX,TDIIDXXX=NEW.TDIIDXXX,TPEIDXXX=NEW.TPEIDXXX WHERE (CLIIDXXX=NEW.CLIIDXXX);
	END IF;
ELSEIF(NEW.MAPCLIXX = 'NO') THEN
	DELETE FROM MAPCARGO.GRM00350 WHERE cliidxxx = NEW.CLIIDXXX;
END IF;

END
$$
DELIMITER ;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `GRM00350`
--
ALTER TABLE `GRM00350`
  ADD PRIMARY KEY (`CLIIDXXX`),
  ADD KEY `CLIIDXXX` (`CLIIDXXX`),
  ADD KEY `idx_GRM_GRM00350_CLIIDXXX` (`CLIIDXXX`),
  ADD KEY `CLINOMXX` (`CLINOMXX`);
COMMIT;
