/*───────────────────────────
  1. TERP0001 – Waybill
───────────────────────────*/
CREATE TABLE `TERP0001` (
  `WAYBILRC` VARCHAR(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Process Code',
  `IDPRCINV` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Process Invoice Code',
  `WAYBILBR` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Broker Reference Number',
  `WAYBILCU` VARCHAR(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Process Customs (ICR1, ICR2 …) ',
  `WAYBILTT` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Means of Transportation',
  `WAYBILTN` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Trip Name',
  `WAYBILTM` VARCHAR(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Master / Booking Number',
  `WAYBILNP` INT(18) NOT NULL COMMENT 'Number of Packages',
  `WAYBILNW` DECIMAL(18,2) NOT NULL COMMENT 'Net Weight kg',
  `WAYBILGW` DECIMAL(18,2) NOT NULL COMMENT 'Gross Weight kg',
  `WAYBILCW` DECIMAL(18,2) NOT NULL COMMENT 'Chargeable Weight kg',
  `WAYBILMS` DECIMAL(18,2) NOT NULL COMMENT 'Measurement m³',
  `WAYBILPO` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Port/Airport Origin',
  `WAYBILPD` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Port/Airport Destination',
  `WAYBILTR` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Trip Number',
  `WAYBILMO` VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Mode of Import Process',
  `EVENTTYP` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Event Type',
  `EVENTDTX` DATE NOT NULL COMMENT 'Event Date',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`WAYBILRC`),
  KEY IDX_WAYBILRC(WAYBILRC),
  KEY `IDPRCINV` (`IDPRCINV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Waybill';

/*───────────────────────────
  2. TERP0002 – Invoice Header
───────────────────────────*/
CREATE TABLE `TERP0002` (
  `INVOICRC` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Invoice Code (Softway)',
  `INVOICTP` VARCHAR(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Process Type (IMPORTACION/EXPORTACION)',
  `INVOICNM` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Invoice Number',
  `INVOICTYP` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Invoice Type (Commercial/Proforma)',
  `INVOICEX` VARCHAR(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Export Type',
  `INVOICNW` DECIMAL(18,2) NOT NULL COMMENT 'Net Weight kg',
  `INVOICGW` DECIMAL(18,2) NOT NULL COMMENT 'Gross Weight kg',
  `INVOICCV` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'COVE Number (MX)',
  `INVOICIN` VARCHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Incoterms',
  `INVOICCU` VARCHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Currency',
  `INVOICPC` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Payment Conditions',
  `INVOICPM` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Payment Modality',
  `INVOICAM` DECIMAL(18,2) NOT NULL COMMENT 'Total Amount',
  `INVOICFN` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Fiscal Number',
  `EVENTTYP` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Event Type',
  `EVENTDTX` DATE NOT NULL COMMENT 'Event Date',
  `INVCERTN` VARCHAR(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Number',
  `INVCERTT` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Type',
  `INVCERTA` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Agreement',
  `INVCERTR` DATE DEFAULT NULL COMMENT 'Certificate Request Date',
  `INVCERTI` DATE DEFAULT NULL COMMENT 'Certificate Issuing Date',
  `INVCERTO` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Observations',
  `INVCERTS` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Signature',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`INVOICRC`),
  KEY IDX_INVOICRC(INVOICRC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Invoice Header';

/*───────────────────────────
  3. TERPI001 – Invoice Item
───────────────────────────*/
CREATE TABLE `TERPI001` (
  `INVITERC` VARCHAR(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Invoice Item Code',
  `IDPRCINV` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Process Code',
  `INVITEKT` VARCHAR(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Internal Control Kit',
  `INVITELN` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Item Line (Alfanum.)',
  `INVITELNI` INT(18) DEFAULT NULL COMMENT 'Item Line (Número)',
  `INVITEPN` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Part Number',
  `INVITEDS` VARCHAR(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Description',
  `INVITEHS` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'HTS',
  `INVITEQY` DECIMAL(18,7) DEFAULT NULL COMMENT 'Quantity',
  `INVITEUP` DECIMAL(18,7) DEFAULT NULL COMMENT 'Unit Price',
  `INVITEMP` DECIMAL(18,7) DEFAULT NULL COMMENT 'Media Price',
  `INVITETP` DECIMAL(18,7) DEFAULT NULL COMMENT 'Total Price',
  `INVITEUN` DECIMAL(18,7) DEFAULT NULL COMMENT 'Unit Net kg',
  `INVITETN` DECIMAL(18,7) DEFAULT NULL COMMENT 'Total Net kg',
  `INVITEUG` DECIMAL(18,7) DEFAULT NULL COMMENT 'Unit Gross kg',
  `INVITETG` DECIMAL(18,7) DEFAULT NULL COMMENT 'Total Gross kg',
  `INVITEMU` VARCHAR(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Unit of Measure',
  `INVITECO` VARCHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Country of Origin',
  `INVITERM` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Export Regime',
  `INVADMNB` VARCHAR(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Admission Declaration #',
  `INVADPRC` VARCHAR(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Admission Process Ref',
  `INVADITM` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Admission Item',
  `INVADSIT` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Admission Sub‑item',
  `INVFRCUR` VARCHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Freight Currency',
  `INVFRVAL` DECIMAL(18,7) DEFAULT NULL COMMENT 'Freight Unit Value',
  `INVINCUR` VARCHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Insurance Currency',
  `INVINVAL` DECIMAL(18,7) DEFAULT NULL COMMENT 'Insurance Unit Value',
  `INVSCCUR` VARCHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Surcharge Currency',
  `INVSCRVL` DECIMAL(18,7) DEFAULT NULL COMMENT 'Surcharge Unit Value',
  `INVDCCUR` VARCHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Deduction Currency',
  `INVDCRVL` DECIMAL(18,7) DEFAULT NULL COMMENT 'Deduction Unit Value',
  `INVDJAIN` VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SIMI Number',
  `INVDJAIT` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SIMI Item',
  `INVDJASU` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'SIMI Sub‑item',
  `INVREPNB` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Action Number (Replacement)',
  `INVREPSI` VARCHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Flag Inventory Replacement (S/N)',
  `INVITEUF` DECIMAL(18,7) DEFAULT NULL COMMENT 'Unity FOB Value',
  `ITEMEXRS` VARCHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Flag Stock Reposition (S/N)',
  `ITEMEXRC` VARCHAR(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Flag Stock Reposition Company',
  `INVITEBN` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Batch Reference',
  `INVITEBD` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Batch Description',
  `INVITEBDT` DATE DEFAULT NULL COMMENT 'Batch Due Date',
  `INVITEBQ` DECIMAL(18,7) DEFAULT NULL COMMENT 'Unity FOB Batch',
  `INVITEBU` DECIMAL(18,7) DEFAULT NULL COMMENT 'Total FOB Batch',
  `ITEMCONR` DECIMAL(18,7) DEFAULT NULL COMMENT 'Value Consumed Inside Regime',
  `ITEMCONI` DECIMAL(18,7) DEFAULT NULL COMMENT 'Value Consumed Outside Regime',
  `INVICNCM` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Origin NCM',
  `INVICNAL` VARCHAR(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Origin NALADI',
  `INVICDES` VARCHAR(675) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Origin Desc.',
  `INVICORI` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Origin % 1',
  `INVICPER` VARCHAR(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Certificate Origin % 2',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`INVITERC`,`IDPRCINV`),
  KEY IDX_INVITERC(INVITERC),
  KEY `IDPRCINV` (`IDPRCINV`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Invoice Item';

/*───────────────────────────
  4. TERPG002 – Entity
───────────────────────────*/
CREATE TABLE `TERPG002` (
  `PRCSCODE` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Process Code',
  `ENTITYRC` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Entity Reference Code',
  `ENTITYTP` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Entity Type',
  `ENTITYTI` VARCHAR(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Entity Tax ID',
  `ENTITYNM` VARCHAR(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Entity Name',
  `ENTITYCO` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Entity Country',
  `ENTITYAD` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Entity Address',
  `ENTITYAN` DECIMAL(18,2) DEFAULT NULL COMMENT 'Address Number',
  `ENTITYNB` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Neighborhood',
  `ENTITYSU` VARCHAR(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Subsidiary',
  `ENTITYCT` VARCHAR(35) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'City',
  `ENTITYST` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'State',
  `ENTITYPC` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Postal Code',
  `ENTITYPH` VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Phone',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`PRCSCODE`),
  KEY IDX_PRCSCODE(PRCSCODE),
  KEY `ENTITYRC` (`ENTITYRC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Entity';

/*───────────────────────────
  5. TERPG001 – Expense
───────────────────────────*/
CREATE TABLE `TERPG001` (
  `PRCSCODE` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Process Code',
  `EXPENSET` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Expense Type',
  `EXPENSEV` DECIMAL(18,2) NOT NULL COMMENT 'Expense Value',
  `EXPENSEC` VARCHAR(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Currency',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`PRCSCODE`,`EXPENSET`),
  KEY IDX_PRCSCODE(PRCSCODE),
  KEY `EXPENSET` (`EXPENSET`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Expense';

/*───────────────────────────
  6. TERPW001 – Container
───────────────────────────*/
CREATE TABLE `TERPW001` (
  `WAYBILRC` VARCHAR(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Process Code',
  `CONTNUMB` VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Container Number',
  `CONTSEAL` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Seal Number',
  `CONTFLX1` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'FlexField1',
  `CONTFLX2` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'FlexField2',
  `CONTFLX3` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'FlexField3',
  `CONTFLX4` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'FlexField4',
  `CONTFLX5` VARCHAR(25) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'FlexField5',
  `CONTSEAX` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Seal Number (Alt)',
  `CONTTYPE` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Container Type',
  `CONTDESC` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Description',
  `CONTBULK` DECIMAL(18,2) DEFAULT NULL COMMENT 'Number of Bulks',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`WAYBILRC`),
  KEY IDX_WAYBILRC(WAYBILRC),
  KEY `CONTNUMB` (`CONTNUMB`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Container';

/*───────────────────────────
  7. TERPP001 – Payment Detail
───────────────────────────*/
CREATE TABLE `TERPP001` (
  `INVOICRC` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Invoice Code',
  `PAYDETTP` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Payment Detail Type',
  `PAYDETBD` DATE DEFAULT NULL COMMENT 'Base Date',
  `PAYDETND` VARCHAR(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Days After Base Date',
  `PAYDETDD` DATE DEFAULT NULL COMMENT 'Due Date',
  `PAYDETPR` DECIMAL(18,2) DEFAULT NULL COMMENT '% of Invoice',
  `PAYDETAM` DECIMAL(18,2) DEFAULT NULL COMMENT 'Amount',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`INVOICRC`),
  KEY `INVOICRC` (`INVOICRC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Payment Detail';

/*───────────────────────────
  8. TERPI002 – Invoice Item Export Returns
───────────────────────────*/
CREATE TABLE `TERPI002` (
  `INVITERC` VARCHAR(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Invoice Item Code',
  `EXRTDCLN` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Export Declaration Number',
  `EXRTDLIT` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Export Declaration Item',
  `EXRTDLSU` VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Export Declaration Sub‑item',
  `EXRTDLQT` DECIMAL(18,7) DEFAULT NULL COMMENT 'Sub‑item Quantity',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`INVITERC`),
  KEY IDX_INVITERC(INVITERC),
  KEY `EXRTDCLN` (`EXRTDCLN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Invoice Item Export Returns';

/*───────────────────────────
  9. TERPI004 – Invoice Item Duty
───────────────────────────*/
CREATE TABLE `TERPI004` (
  `INVITERC` VARCHAR(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Invoice Item Code',
  `DUTYTYPX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Duty Type',
  `DUTYPERC` DECIMAL(18,2) DEFAULT NULL COMMENT 'Duty %',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`INVITERC`),
  KEY IDX_INVITERC(INVITERC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Invoice Item Duty';

/*───────────────────────────
 10. TERPI003 – Invoice Item Composition
───────────────────────────*/
CREATE TABLE `TERPI003` (
  `INVITERC` VARCHAR(18) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Invoice Item Code',
  `INVITESN` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Serial Number',
  `INVIREGI` VARCHAR(4000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Regime Composition',
  `ITEMDJXX` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Declaración Jurada #',
  `REGUSRXX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creación',
  `REGFECXX` DATE NOT NULL COMMENT 'Fecha Creación',
  `REGHORXX` TIME NOT NULL COMMENT 'Hora Creación',
  `REGUSRMX` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Modificación',
  `REGFECMX` DATE NOT NULL COMMENT 'Fecha Modificación',
  `REGHORMX` TIME NOT NULL COMMENT 'Hora Modificación',
  `REGESTXX` ENUM('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado',
  `REGSTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`INVITERC`),
  KEY IDX_INVITERC(INVITERC),
  KEY `INVITESN` (`INVITESN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Invoice Item Composition';
