CREATE TABLE IF NOT EXISTS `BDTG2025` (
  `CONSBDTG` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Consecutivo',
  `PROIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `BDGTTIPO` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de Trazabilidad',
  `PRODESXX` text COLLATE utf8_unicode_ci NOT NULL,
  `PROUSRXX` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Usuario que realiza la Trazabilidad',
  `DOCNROXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `REGFECMR` date NOT NULL COMMENT 'Fecha de Modificacion del Registro Para RIO',
  `REGHORMR` time NOT NULL COMMENT 'Hora de Modificacion del Registro Para RIO',
  `FECCREXX` date NOT NULL,
  `HORCREXX` time NOT NULL,
  `REGUSRXX` varchar(12) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `REGFECXX` date NOT NULL DEFAULT '0000-00-00',
  `REGMODXX` date NOT NULL DEFAULT '0000-00-00',
  `REGHORXX` time NOT NULL,
  `REGESTXX` varchar(8) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFICADO',
  PRIMARY KEY (`CONSBDTG`,`PROIDXXX`,`DOCNROXX`),
  KEY `DOCNROXX` (`DOCNROXX`),
  KEY `PROIDXXX` (`PROIDXXX`,`DOCNROXX`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Bodega Trazabilidad General' AUTO_INCREMENT=4312820 ;

