
CREATE TABLE IF NOT EXISTS `MDSE2025` (
  `DOCNROXX` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'IDENTIFICACION DE LA OPERACION',
  `NUMSAEXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NUMERO DE LA SAE',
  `NUMSAENS` smallint(6) NOT NULL COMMENT 'NUMERO DE SERIE CASILLA 150',
  `NUMSAEPR` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NUMERO DE PROGRAMA CASILLA 151',
  `NUMSAERE` enum('','SI','NO') COLLATE utf8_unicode_ci NOT NULL COMMENT 'REPOSICION CASILLA 152',
  `NUMSAECI` smallint(3) NOT NULL COMMENT 'No DE CUADRO INSUMO PRODUCTO(CIP) CASILLA 153',
  `NUMSAEPO` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'No DEL PRODUCTO CASILLA 154',
  `NUMSAECP` decimal(7,2) NOT NULL COMMENT 'CANTIDAD PRODUCTO A EXPORTAR POR CIP CASILLA 155',
  `NUMSAEVN` decimal(7,7) NOT NULL COMMENT 'VALOR AGREGADO NACIONAL (VAN) EN USD CASILLA 156',
  `NUMSAEVE` decimal(7,7) NOT NULL COMMENT 'VALOR INSUMO EXTERNO (VIE) EN USD CASILLA 157',
  `REGUSRXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') COLLATE utf8_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado',
  PRIMARY KEY (`DOCNROXX`,`NUMSAEXX`,`NUMSAENS`),
  KEY `DOCNROXX` (`DOCNROXX`),
  KEY `NUMSAEXX` (`NUMSAEXX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='DATOS DE SAE Y DEX VS MANEJOS ESPECIALES';


