

CREATE TABLE IF NOT EXISTS `SCTC2025` (
  `TARIDXXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Id Tarea',
  `PROIDORI` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ID DEL PROCESO ORIGEN',
  `SUBIDORI` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Subproceso Origen',
  `ASUIDXXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `TARNITXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NIT DE ALE EMPRESA DUEÑA DEL GRUPO',
  `SUCIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'SUCURSAL',
  `TRAIDXXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'NUMERO DE TRAMITE',
  `SUFIDXXX` varchar(3) COLLATE utf8_unicode_ci NOT NULL COMMENT 'SUFIJO',
  `CLIIDXXX` varchar(13) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nit del Cliente Si Aplica',
  `PROIDXXX` varchar(13) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nit del Proveedor Si Aplica',
  `TARPRIXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'PRIORIDAD',
  `TARAVFEC` date NOT NULL COMMENT 'FECHA DE AVISO',
  `TARAVHOR` time NOT NULL COMMENT 'HORA DE AVISO',
  `PROIDDES` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ID PROCESO DESTINO',
  `SUBIDDES` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Subproceso Destino',
  `USRIDDES` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'USUARIO DESTINO',
  `TARCANXX` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cantidad de Tramites',
  `TARCANSO` varchar(10) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Cantidad Solucionada',
  `TARMEMOX` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Matriz se Datos Auxiliares',
  `TARMEMO2` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Memo Auxiliar 2',
  `TARMEMO3` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `TARANTXX` varchar(20) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tarea Nacimiento',
  `TARTIPXX` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Tipo de Tarea',
  `TARFECSO` date NOT NULL COMMENT 'Fecha de Solucion futura para una tarea en espera',
  `ASUCFXXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Bloqueo de Cambio de Fecha en la solucion de la tarea',
  `TARUSRCR` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Usuario Creacion de Tarea',
  `TARVIBUE` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Vistos Buenos de la Tera de Elaboracion de Registros de Importacion',
  `TARPLANT` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Plantillas de la Tarea de elaboracion de registros de Importacion',
  `TARPRODU` text COLLATE utf8_unicode_ci NOT NULL COMMENT 'Productos de la tarea de elaboracion de registros de Importacion',
  `TARDIGSA` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'la Digitacion de la tarea fue satisfactoria',
  `TARMENSX` varchar(250) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Mensajero Asignado para Resolver esta Tarea',
  `TARZOMEN` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Zona de Mensajeria',
  `TARMODFU` varchar(50) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Modo de Funcionamiento en Mensageria o entregar o recoger Documentos',
  `TARREAXX` varchar(2) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Si se realizo o no la tarea de Mensajeria',
  `CATARIDX` int(11) NOT NULL COMMENT 'Categoria',
  `REGUSRXX` varchar(30) COLLATE utf8_unicode_ci NOT NULL COMMENT 'USUARIO CREACION DE REGISTRO',
  `REGFECXX` date NOT NULL DEFAULT '0000-00-00' COMMENT 'FECHA DE REGISTRO',
  `REGMODXX` date NOT NULL DEFAULT '0000-00-00' COMMENT 'FECHA DE MODIFICACION DE REGISTRO',
  `REGHORXX` varchar(5) COLLATE utf8_unicode_ci NOT NULL COMMENT 'HORA DE REGISTRO',
  `REGESTXX` varchar(15) COLLATE utf8_unicode_ci NOT NULL COMMENT 'ESTADO DE REGISTRO',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFICADO',
  PRIMARY KEY (`TARIDXXX`),
  KEY `TRAIDXXX` (`TRAIDXXX`),
  KEY `ASUIDXXX` (`ASUIDXXX`),
  KEY `CLIIDXXX` (`CLIIDXXX`),
  KEY `PROIDXXX` (`PROIDXXX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


