-- Base de datos: `CIMADEV`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `MDOI2025`
--

DROP TABLE IF EXISTS `MDOI2025`;
CREATE TABLE `MDOI2025` (
  `DOCNROXX` int NOT NULL COMMENT 'NUMERO DEL DO(MDOSYYYY)',
  `TOKIDXXX` int NOT NULL COMMENT 'ID DEL TIPO DE KPI',
  `INOPIDXX` int NOT NULL COMMENT 'ID DEL INDICADOR',
  `FORCALID` int NOT NULL COMMENT 'ID DE LA FORMULA DEL CALCULO',
  `LIMINFFE` date NOT NULL COMMENT 'FECHA DE LIMITE INFERIOR',
  `LIMINHOR` time NOT NULL COMMENT 'HORA DE LIMITE INFERIOR',
  `RESESPFE` date NOT NULL COMMENT 'FECHA DE RESULTADO ESPERADO',
  `RESESPHO` time NOT NULL COMMENT 'HORA DE RESULTADO ESPERADO',
  `VALORESP` decimal(3,2) NOT NULL COMMENT 'VALOR DEL RESULTADO ESPERADO',
  `LIMSUPFE` date NOT NULL COMMENT 'FECHA DE LIMITE SUPERIOR',
  `LIMSUPHO` time NOT NULL COMMENT 'HORA LIMITE SUPERIOR',
  `CUMPLEXX` enum('','ERROR_DATOS','SI','NO','POR VENCER','VENCIDO') COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'RESULTADO DEL ANALISIS DEL INDICADOR',
  `RESOBTEX` decimal(7,3) NOT NULL COMMENT 'VALOR DEL RESULTADO OBTENIDO',
  `UNIMEDID` int NOT NULL COMMENT 'ID DE LA UNIDAD DE MEDIDA(CIPO0096)',
  `REGUSRXX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario Creacion del Registro',
  `REGFECXX` date NOT NULL COMMENT 'Fecha de Creacion del Registro',
  `REGHORXX` time NOT NULL COMMENT 'Hora de Creacion del Registro',
  `REGUSRMX` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Usuario de Modificacion',
  `REGFECMX` date NOT NULL COMMENT 'Fecha de Modificacion del Registro',
  `REGHORMX` time NOT NULL COMMENT 'Hora de Modificacion del Registro',
  `REGESTXX` enum('ACTIVO','INACTIVO') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Estado del Registro',
  `REGSTAMP` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Modificado'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='OPERACIONES VS INDICADORES' ROW_FORMAT=DYNAMIC;

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `MDOI2025`
--
ALTER TABLE `MDOI2025`
  ADD PRIMARY KEY (`DOCNROXX`,`TOKIDXXX`,`INOPIDXX`,`FORCALID`),
  ADD KEY `DOCNROXX` (`DOCNROXX`),
  ADD KEY `TOKIDXXX` (`TOKIDXXX`),
  ADD KEY `INOPIDXX` (`INOPIDXX`),
  ADD KEY `FORCALID` (`FORCALID`);
COMMIT;